/*
 * File: app/store/ProductStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.store.AllBookingsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.AllBookingsStore',

    requires: [
        'KerberosBooking.model.AllBookingsModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'AllBookingsStore',
            model: 'KerberosBooking.model.AllBookingsModel',
            proxy: {
	                type: 'ajax',
	                url: 'getAllShipments',
	                method: 'POST',
	                extraParams:{
	                        username: localStorage.getItem('name'),
	                        jsonString: '{}'
	                },
	                reader: {
	                    type: 'json',
	                    idProperty: 'shipmentNum'
	                },
	                actionMethods: {
	                    create : 'POST',
	                    read   : 'POST', // by default GET
	                    update : 'POST',
	                    destroy: 'POST'
	                }
            }
        }, cfg)]);
        
    }
});