/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.Img'
    ],

    autoScroll: true,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: 'absolute',
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'label',
                            x: 320,
                            y: 70,
                            id: 'txt.label',
                            itemId: 'txt.label',
                            text: 'Press the Button :D'
                        },
                        {
                            xtype: 'button',
                            x: 330,
                            y: 120,
                            id: 'btn.Txt',
                            itemId: 'btn.Txt',
                            text: 'PRESS ME',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'image',
                            x: 240,
                            y: 180,
                            draggable: true,
                            height: 201,
                            hidden: true,
                            id: 'img.Gif',
                            itemId: 'img.Gif',
                            width: 260,
                            src: '%5Capp%5Cimages%5Csmol.gif',
                            listeners: {
                                move: {
                                    fn: me.onImageMove,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            x: 330,
                            y: 120,
                            hidden: true,
                            id: 'btn.Img',
                            itemId: 'btn.Img',
                            text: 'PRESS ME',
                            listeners: {
                                click: {
                                    fn: me.onImgClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var text = Ext.getCmp('txt.label');
        var img = Ext.getCmp('img.Gif');


        //img.setDisabled(false);
        img.setVisible(false);
        img.show();
        text.setText("Drag the Picture");
    },

    onImageMove: function(component, x, y, eOpts) {
        var text = Ext.getCmp('txt.label');
        var btnTxt = Ext.getCmp('btn.Txt');
        var btnImg = Ext.getCmp('btn.Img');


        text.setText("Click the picture");

        btnTxt.hide();
        btnImg.show();

        console.log(component.getLocalXY());
    },

    onImgClick: function(button, e, eOpts) {
        var panell = Ext.create('MyApp.view.MyWindow', {});

        panell.show();
    }

});