/*
 * File: app/controller/AdminController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.AdminController', {
    extend: 'Ext.app.Controller',

    control: {
        "#home": {
            click: 'onHomeClick'
        },
        "#kerberos": {
            click: 'onKerberosClick'
        },
        "#search": {
            click: 'onSearchClick'
        },
        "#create": {
            click: 'onCreateClick'
        },
        "#users": {
            click: 'onUsersClick'
        },
        "#about": {
            click: 'onAboutClick'
        },
        "#submitSearchBtn": {
        	click: 'onSubmitSearchBtn'
        },
        "#adminLogout": {
        	click: 'onAdminLogout'
        },
        "#deleteUser": {
        	click: 'onDeleteUser'
        },
        "#editUser": {
        	click: 'onEditUser'
        },
        "#resetSearchBtn": {
        	click: 'onResetSearchBtn'
        }
        
        
        
    },

    
    onHomeClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('adminPanel')[0];
        var center = viewport.down('[region=center]'),
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        userPanel = Ext.ComponentQuery.query('viewUsersPanel')[0];



        var view = Ext.create('MyPanel');

        center.remove(userPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        center.remove(viewPanel);
        center.add(view);
    },

    onKerberosClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('adminPanel')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        userPanel = Ext.ComponentQuery.query('viewUsersPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('myHomePanel');

        console.log(viewport);

        center.remove(userPanel);
        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(createPanel);
        center.add(view);
    },

    onSearchClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('adminPanel')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];
            userPanel = Ext.ComponentQuery.query('viewUsersPanel')[0];

            view = Ext.create('viewBookingPanel');

        console.log(viewport);

        center.remove(userPanel);
        center.remove(mainPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        center.add(view);
    },

    onCreateClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('adminPanel')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
        	userPanel = Ext.ComponentQuery.query('viewUsersPanel')[0];

            view = Ext.create('createBkgPanel');

        console.log(viewport);
        center.remove(userPanel);
        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(homePanel);
        center.add(view);
    },

    onUsersClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('adminPanel')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
        	userPanel = Ext.ComponentQuery.query('createBkgPanel')[0];

            view = Ext.create('viewUsersPanel');

        console.log(viewport);
        center.remove(userPanel);
        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(homePanel);
        center.add(view);
        
        var data = localStorage.getItem('name');
        console.log(data);
    },

    onAboutClick: function(button, e, eOpts) {

    	var viewport = Ext.ComponentQuery.query('adminPanel')[0],
        center = viewport.down('[region=center]'),
        mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
        viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
        homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
    	userPanel = Ext.ComponentQuery.query('createBkgPanel')[0];

        view = Ext.create('updateUser');

    console.log(viewport);
    center.remove(userPanel);
    center.remove(mainPanel);
    center.remove(viewPanel);
    center.remove(homePanel);
    center.add(view);
    
    },
    onSubmitSearchBtn: function(button, e, eOpts) {
    	
    	
    	var forms = Ext.getCmp('searchUsersPanel');
    	var val = forms.getValues(),
        value = Ext.encode(forms.getValues()),
        grid = Ext.getCmp('userGrid');
    	grid.getStore().reload({
    		  params:{
           	   username: val.username, 
           	   firstName: val.fname ,
           	   lastName: val.lname,
           	   role:""
             },
			callback: function(){
				grid.getView().refresh();
			}
		});
    	
    	console.log(forms.getValues());
    	grid.getView().refresh();
    },
    onAdminLogout: function(button, e, eOpts) {
    	var user = localStorage.getItem('name');
	  Ext.Msg.confirm("Confirmation", "Do you really want to logout " + user + " ?" , function(btnText){
    	      if(btnText === "no"){
    	    	  localStorage.setItem('name',username);
    	      }
    	      else if(btnText === "yes"){
    	    	  localStorage.clear();
    	          window.location.reload();
    	    	  
    	      }
    	  }, this);
    }
    
    ,
    onDeleteUser: function(button, e, eOpts) {
    	
        var grid = Ext.getCmp('userGrid');
        var store = grid.getStore();
        var selection = grid.getSelectionModel().getSelection()[0];
        
	  Ext.Msg.confirm("Confirmation", "Do you really want to delete user " + selection.data.username + " ?" , function(btnText){
    	      if(btnText === "no"){
    	    	  
    	      }
    	      else if(btnText === "yes"){
    	    	  Ext.Ajax.request({
    	              url: 'deleteUser',
    	              method: 'POST',
    	              params:{
    	            	  username:   selection.data.username
    	              },
    	              callback: function(options, success, response) {
    	            	      	  
    	            	  alert('User has been deleted');
    	            	  if (selection) {
    	                      store.remove(selection);
    	                  }
    	            
    	              },failure : function(response) {

    	                  console.log("response", response);

    	              }

    	              });
    	    	  
    	      }
    	  }, this);
	  grid.getView().refresh();
    },
    
    onEditUser: function(button, e, eOpts) {
    	 Ext.create('KerberosBooking.view.RegisterForm').show();

    	 Ext.getCmp('registerForm').setTitle('Update User');
    	 
    	 Ext.getCmp('registerButton').setText('Update');
    	
    	var grid = Ext.getCmp('userGrid');
        var store = grid.getStore();
        var selection = grid.getSelectionModel().getSelection()[0];
        
        Ext.getCmp('firstName').setValue(selection.data.firstName);
        Ext.getCmp('lastName').setValue(selection.data.lastName);
        Ext.getCmp('email').setValue(selection.data.email);
        Ext.getCmp('password').setValue(selection.data.password);
        Ext.getCmp('username').setValue(selection.data.username);
        Ext.getCmp('contactNo').setValue(selection.data.contactNo);

        
        if(selection.data.role == 'Admin'){
        	Ext.getCmp('radioAdminUser').setValue(selection.data.role)
        } else if(selection.data.role == 'CSV'){
        	Ext.getCmp('radioCSVUser').setValue(selection.data.role)
        } else if(selection.data.role == 'Customer'){
        	Ext.getCmp('radioCustomerUser').setValue(selection.data.role)
        }
        
    	
    },
    
    onResetSearchBtn: function(button, e, eOpts) {
    	var forms = button.up('form');
    	 forms.reset();
    	 KerberosBooking.app.getController('AdminController').onSubmitSearchBtn();
    }
    

});
