/*
 * File: app/controller/createBooking.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.createBooking', {
    extend: 'Ext.app.Controller',

    control: {
        "#addCntr": {
            click: 'onAddCntrClick'
        },
        "#deleteCntr": {
            click: 'onDeleteCntrClick'
        },
        "#copyCntr": {
            click: 'onCopyCntrClick'
        }
    },

    onAddCntrClick: function(button, e, eOpts) {
        var grid = Ext.getCmp('createContainer');
            grid.getStore().add({
            	refNum  : null,
            	cntrType  : null,
            	grossWt : null,
            	netWt : null,
            	wtUnit : 'KG'

                   });


              grid.getView().refresh();

    },

    onDeleteCntrClick: function(button, e, eOpts) {
        var grid = Ext.getCmp('createContainer');
        var store = grid.getStore();
        var selection = grid.getSelectionModel().getSelection()[0];

        console.log(selection);
                if (selection) {
                    store.remove(selection);
                }
    },

    onCopyCntrClick: function(button, e, eOpts) {
        // copy the selected record
        var grid = Ext.getCmp('createContainer');
        var store = grid.getStore();
        var copy = grid.getSelectionModel().getSelection()[0];

        console.log(copy.data.containerNumber);
        // inserts the copied record at the end of the grid

        store.add({
        	refNum  : copy.data.refNum,
        	cntrType  : copy.data.cntrType,
        	grossWt : copy.data.grossWt,
        	netWt : copy.data.netWt,
        	wtUnit : copy.data.wtUnit});
        grid.getView().refresh();
        //grid.getStore().insert(grid.store.data.length, new grid.store.recordType(copy.data));
    }

});
