/*
 * File: app/controller/createBooking.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.FindBookingsController', {
    extend: 'Ext.app.Controller',

    control: {
//        "#addCntr": {
//            click: 'onAddCntrClick'
//        },
//        "#deleteCntr": {
//            click: 'onDeleteCntrClick'
//        },
        "#viewBkgBtn": {
            click: 'onViewBtnClick'
        },
    	"#searchBkgBtn": {
          click: 'onSearchBkgBtnClick'
    	}
    },

    onSearchBkgBtnClick: function(button, e, eOpts) {
    	var forms = button.up('form'),
        value = Ext.encode(forms.getValues()),
        grid = Ext.getCmp('bkgGrid');
    	grid.getStore().reload({
    		params:{
    			username:localStorage.getItem('name'),
    			jsonString: value
			},
			callback: function(){
				grid.getView().refresh();
			}
		});
    },

    onViewBtnClick: function(button, e, eOpts) {
    	var forms = button.up('form'),
        value = Ext.encode(forms.getValues()),
        grid = Ext.getCmp('bkgGrid');
    	var bookingNum = grid.getSelection()[0].data.shipmentNum;
    	grid.getStore().reload({
    		params:{
    			username:localStorage.getItem('name'),
    			jsonString: value
			},
			callback: function(){
				grid.getView().refresh();
			}
		});
    },
//
//    onCopyCntrClick: function(button, e, eOpts) {
//        // copy the selected record
//        var grid = Ext.getCmp('createContainer');
//        var store = grid.getStore();
//        var copy = grid.getSelectionModel().getSelection()[0];
//
//        console.log(copy.data.containerNumber);
//        // inserts the copied record at the end of the grid
//
//        store.add({
//                    referenceNumber  : copy.data.referenceNumber,
//                       containerNumber  : copy.data.containerNumber,
//                       grossWeight : copy.data.grossWeight,
//                       netWeight : copy.data.netWeight,
//                       weightUnit : copy.data.weightUnit});
//        grid.getView().refresh();
//        //grid.getStore().insert(grid.store.data.length, new grid.store.recordType(copy.data));
//    }

});
