/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.HomeController', {
    extend: 'Ext.app.Controller',

    control: {
        "#logBtn": {
            click: 'onLogBtnClick'
        },
        "#viewBtn": {
            click: 'onViewBtnClick'
        },
        "#loginBtn": {
            click: 'onLoginBtnClick'
        },
        "#homeBtn": {
            click: 'onHomeBtnClick'
        },
        "#kerberosBtn": {
            click: 'onKerberosBtnClick'
        },
        "#createBtn": {
            click: 'onCreateBtnClick'
        },
        "#aboutBtn": {
            click: 'onAboutBtnClick'
        },
        "#validateResetBtn": {
            click: 'onValidateResetBtnClick'
        },
        "#createResetBtn": {
            click: 'onCreateResetBtnClick'
        }
    },

    onLogBtnClick: function(button, e, eOpts) {
                var username = Ext.getCmp('usernameTxt').getValue(); //get value of username
                var password = Ext.getCmp('passwordTxt').getValue(); // get value of password
                var loginView = Ext.getCmp('headerPanel');
                var form = button.up('form'),				// Register form
                formWindow = button.up('window');

                //TODO: Login using server-side authentication service
                Ext.Ajax.request({
                    url: 'login',
                    method: 'POST',
                    params:{
                        username:   username,
                        password:	password
                    },
                    callback: function(options, success, response) {

                        // console.log(response.responseText);

                         var data = Ext.decode(response.responseText),
                         access = data.isUserValid + data.canCreateBooking + data.canViewBooking + data.canManageUsers;
                         
                         console.log(data.isUserValid);
                        if(access == 4){
                            console.log('admin');

                        } else if (access == 3){
                         formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");
                            Ext.getCmp('createBtn').show();

                            Ext.getCmp('viewBtn').show();
                            Ext.getCmp('loginBtn').hide();

                        } else if(access == 2){
                        	formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");

               Ext.getCmp('viewBtn').show();
               Ext.getCmp('loginBtn').hide();
                        } else{
                        	console.log(access);
                        }

                    },
                    failure : function(response) {

                        console.log("response", response);

                    }
                });

        //Ext.getCmp('createBtn').hide();
    },

    onViewBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('viewBookingPanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        center.add(view);
    },

    onLoginBtnClick: function(button, e, eOpts) {
        //var login = Ext.create('widget.loginform', {});

        // Show window
        //login.show();

        Ext.create('KerberosBooking.view.LoginForm').show();
    },

    onHomeBtnClick: function(button, e, eOpts) {
        // var viewport = Ext.ComponentQuery.query('mainViewport')[0],
        //     center = viewport.down('[region=center]'),
        //     viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
        //     homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
        //     createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        // 	//aboutPanel = Ext.ComponentQuery.query('')[0];

        //     view = Ext.create('MyPanel');

        // //console.log(viewport);

        // center.remove(viewPanel);
        // center.remove(homePanel);
        // center.remove(createPanel);
        // center.add(view);


        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
        var center = viewport.down('[region=center]'),
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];

        var view = Ext.create('MyPanel');

        center.remove(homePanel);
        center.remove(createPanel);
        center.remove(viewPanel);
        center.add(view);
    },

    onKerberosBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('myHomePanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(createPanel);
        center.add(view);
    },

    onCreateBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('createBkgPanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(homePanel);
        center.add(view);
    },

    onValidateResetBtnClick: function(button, e, eOpts) {
        //var form = button.up('createBookingPanel'),
          var forms = button.up('form'),
       //values = form.getValues(),
            value = forms.getValues();

          var createBooking = Ext.encode(value);
      //console.log(values);
      console.log(createBooking);
  },

  onCreateResetBtnClick: function(button, e, eOpts) {

  }

});
