/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.HomeController', {
    extend: 'Ext.app.Controller',

    control: {
        "#logBtn": {
            click: 'onLogBtnClick'
        },
        "#viewBtn": {
            click: 'onViewBtnClick'
        },
        "#loginBtn": {
            click: 'onLoginBtnClick'
        },
        "#homeBtn": {
            click: 'onHomeBtnClick'
        },
        "#kerberosBtn": {
            click: 'onKerberosBtnClick'
        },
        "#createBtn": {
            click: 'onCreateBtnClick'
        },
        "#aboutBtn": {
            click: 'onAboutBtnClick'
        },
        "#validateResetBtn": {
            click: 'onValidateResetBtnClick'
        },
        "#createResetBtn": {
            click: 'onCreateResetBtnClick'
        },
        "#registerButton": {
            click: 'onRegisterButtonClick'
        },
        "#logoutBtn": {
        	click: 'onLogoutBtnClick'
        }
    },


    onLogBtnClick: function(button, e, eOpts) {
                var username = Ext.getCmp('usernameTxt').getValue();
                var password = Ext.getCmp('passwordTxt').getValue(); 
                var loginView = Ext.getCmp('headerPanel');
                var form = button.up('form'),				
                formWindow = button.up('window');
                localStorage.setItem('name',username);

                Ext.Ajax.request({
                    url: 'login',
                    method: 'POST',
                    params:{
                        username:   username,
                        password:	password
                    },
                    callback: function(options, success, response) {

                         var data = Ext.decode(response.responseText),
                         access = data.isUserValid + data.canCreateBooking + data.canViewBooking + data.canManageUsers;
                         
                        if(access == 4){
                        
                        	formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");
                            Ext.getCmp('hometoolbar').hide();
                            
                            var viewport = Ext.ComponentQuery.query('mainViewport')[0],
                            center = viewport.down('[region=center]'),
                            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
                            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
                            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
                        	//aboutPanel = Ext.ComponentQuery.query('')[0];

                            view = Ext.create('adminPanel');

                        console.log(viewport);

                        center.remove(mainPanel);
                        center.remove(homePanel);
                        center.remove(createPanel);
                        center.add(view);

                        var viewport2 = Ext.ComponentQuery.query('adminPanel')[0];
                        var center2 = viewport2.down('[region=center]');

                        var view2 = Ext.create('MyPanel');

                        center2.add(view2);

                        } else if (access == 3){
                         formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");
                            Ext.getCmp('createBtn').show();

                            Ext.getCmp('viewBtn').show();
                            Ext.getCmp('loginBtn').hide();
                            Ext.getCmp('logoutBtn').show();


                        } else if(access == 2){
                        	formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");

               Ext.getCmp('viewBtn').show();
               Ext.getCmp('loginBtn').hide();
               Ext.getCmp('logoutBtn').show();

                        } else{
                        	console.log(access);
                        }

                    },
                    failure : function(response) {

                        console.log("response", response);

                    }
                });

       

    },

    onViewBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            viewPanel = Ext.ComponentQuery.query('FindBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	
            

        console.log(viewport);
        center.remove(mainPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        center.remove(viewPanel);
        
        var view = Ext.create('FindBookingPanel');
        center.add(view);
    },

    onLoginBtnClick: function(button, e, eOpts) {


        Ext.create('KerberosBooking.view.LoginForm').show();
    },

    onHomeBtnClick: function(button, e, eOpts) {
        //     viewPanel = Ext.ComponentQuery.query('FindBookingPanel')[0],


        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
        center = viewport.down('[region=center]'),
        mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
        homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
        viewPanel = Ext.ComponentQuery.query('FindBookingPanel')[0],
        createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];

        

        center.remove(homePanel);
        center.remove(createPanel);
        center.remove(viewPanel);
        center.remove(mainPanel);
        
        var view = Ext.create('MyPanel');
        center.add(view);
    },

    onKerberosBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
        center = viewport.down('[region=center]'),
        mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
        homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
        viewPanel = Ext.ComponentQuery.query('FindBookingPanel')[0],
        createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];a
    	//aboutPanel = Ext.ComponentQuery.query('')[0];

        view = Ext.create('myHomePanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(createPanel);
        center.add(view);
    },

    onCreateBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
        center = viewport.down('[region=center]'),
        mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
        homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
        viewPanel = Ext.ComponentQuery.query('FindBookingPanel')[0],
        createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        
        var view = Ext.create('createBkgPanel');
        center.add(view);
        
        
        Ext.getCmp('usernameLog').setValue(localStorage.getItem('name'));
        Ext.getCmp('usernameLog').disbaled(true);
    },

    onValidateResetBtnClick: function(button, e, eOpts) {
          var forms = button.up('form'),
            value = forms.getValues();

          var grid = Ext.getCmp('createContainer');
          var containers = grid.getStore().data;
          var arr = [];

          for (var i =0; i < containers.length; ++i){
              arr.push(containers.items[i].data);
          }
          
          value['container'] = arr;
          var container = Ext.encode(value);
          var test1 = value + arr;

      var createBooking = Ext.encode(value);
      
      console.log(container);
  
      Ext.Ajax.request({
          url: 'createBooking',
          method: 'POST',
          params:{
              jsonString:   createBooking
          },
          callback: function(options, success, response) {
        	      	  
        	  var data = Ext.decode(response.responseText);	
      	  
        	  console.log(data);
        	  console.log(data.serviceResult);        	  
        	  alert('Shipment Number is: ' + data.serviceResult);

        	  forms.reset();
        	  grid.getStore().removeAll();
        	  grid.getStore().sync();
        
          },failure : function(response) {

              console.log("response", response);

          }
          
          });
      
 

  
  },


  onCreateResetBtnClick: function(button, e, eOpts) {
	  var forms = button.up('form'),
      value = forms.getValues();
	  forms.reset();
	  grid.getStore().removeAll();
	  grid.getStore().sync();
  },

  onRegisterButtonClick: function(button, e, eOpts) {

	  
	  console.log(Ext.getCmp('registerButton').getText());
	  
	  
	  if(Ext.getCmp('registerButton').getText() == 'Update'){
		  var form = button.up('form'),				
	      formWindow = button.up('window'),		
	      values = form.getValues();	
		  var   grid = Ext.getCmp('userGrid');
		  var createUser = Ext.encode(values);
		  Ext.Ajax.request({
	          url: 'updateUser',
	          method: 'POST',
	          params:{
	        	  json:   createUser
	          },
	          callback: function(options, success, response) {
	        	  Ext.Msg.alert("Update Success");
	        
	          },failure : function(response) {
	        	  Ext.Msg.alert("Update Failed");
	          }
	          
	          });
		  
	  } else if (Ext.getCmp('registerButton').getText() == 'Register'){
		  
		  var form = button.up('form'),				
	      formWindow = button.up('window'),		
	      values = form.getValues();	
		  var   grid = Ext.getCmp('userGrid');
		  var createUser = Ext.encode(values);
		  Ext.Ajax.request({
	          url: 'createUser',
	          method: 'POST',
	          params:{
	        	  json:   createUser
	          },
	          callback: function(options, success, response) {
	        	  Ext.Msg.alert("Registration Success");
	        
	          },failure : function(response) {
	        	  Ext.Msg.alert("Registration Failed");
	          }
	          
	          });
	  }
	  
		  grid.getView().refresh();
                  formWindow.destroy();
                  KerberosBooking.app.getController('AdminController').onSubmitSearchBtn();

                  
  },
  onLogoutBtnClick: function(button, e, eOpts) {
  
  var user = localStorage.getItem('name');
  
  
  Ext.Msg.confirm("Confirmation", "Do you really want to logout " + user + " ?" , function(btnText){
      if(btnText === "no"){
    	  localStorage.setItem('name',username);
      }
      else if(btnText === "yes"){
    	  localStorage.clear();
    	  Ext.getCmp('loginBtn').show();
          Ext.getCmp('logoutBtn').hide();
          window.location.reload();
    	  
      }
  }, this);
  }
});
