/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    onGraphIdClick: function(item, e, eOpts) {
        var getViewport = Ext.ComponentQuery.query('gridViewport');
        console.log('hannah222');
        var showPanel= Ext.create('MyApp.view.MyViewport2', {});

        showPanel.show();

    },

    onHomeIdClick: function(item, e, eOpts) {


        var getViewport = Ext.ComponentQuery.query('gridViewport');

            //Ext.getCmp('gridViewport');

        console.log('hannahbang');
        //getViewport.show();
        var panell = Ext.create('MyApp.view.MyViewport', {});

        panell.show();
        //Ext.getCmp('homeViewport').add(panell);
    },

    onGraphId2Click: function(item, e, eOpts) {
        var getViewport = Ext.ComponentQuery.query('gridViewport');
        console.log('hannah222');
        var showPanel= Ext.create('MyApp.view.MyViewport2', {});

        showPanel.show();

    },

    onHomeId2Click: function(item, e, eOpts) {


        var getViewport = Ext.ComponentQuery.query('gridViewport');

            //Ext.getCmp('gridViewport');

        console.log('hannahbang');
        //getViewport.show();
        var panell = Ext.create('MyApp.view.MyViewport', {});

        panell.show();
        //Ext.getCmp('homeViewport').add(panell);
    },

    onGridId2Click: function(item, e, eOpts) {
        var getViewport = Ext.ComponentQuery.query('gridViewport');

            //Ext.getCmp('gridViewport');

        console.log('hannahbang');
        //getViewport.show();
        var panell = Ext.create('MyApp.view.MyViewport1', {});

        panell.show();
        //Ext.getCmp('homeViewport').add(panell);
    },

    onReadBtnClick: function(button, e, eOpts) {

        var panell = Ext.create('MyApp.view.MyWindow', {});

        panell.show();

    },

    onGridIdClick: function(item, e, eOpts) {
        console.log('hannahbang');
        //getViewport.show();
        var homePanel = Ext.create('MyApp.view.MyViewport', {});
        var panell = Ext.create('MyApp.view.MyViewport1', {});

        homePanel().removeAll();


        panell.show();


    },

    init: function(application) {
        this.control({
            "#graphId": {
                click: this.onGraphIdClick
            },
            "#homeId": {
                click: this.onHomeIdClick
            },
            "#graphId2": {
                click: this.onGraphId2Click
            },
            "#homeId2": {
                click: this.onHomeId2Click
            },
            "#gridId2": {
                click: this.onGridId2Click
            },
            "#readBtn": {
                click: this.onReadBtnClick
            },
            "#gridId": {
                click: this.onGridIdClick
            }
        });
    }

});
