
package com.oocl.ita.gervajo.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcCatalogue", targetNamespace = "http://ws.gervajo.ita.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcCatalogue {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalcMethods", targetNamespace = "http://ws.gervajo.ita.oocl.com/", className = "com.oocl.ita.gervajo.ws.GetCalcMethods")
    @ResponseWrapper(localName = "getCalcMethodsResponse", targetNamespace = "http://ws.gervajo.ita.oocl.com/", className = "com.oocl.ita.gervajo.ws.GetCalcMethodsResponse")
    @Action(input = "http://ws.gervajo.ita.oocl.com/CalcCatalogue/getCalcMethodsRequest", output = "http://ws.gervajo.ita.oocl.com/CalcCatalogue/getCalcMethodsResponse")
    public List<String> getCalcMethods();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAnswer", targetNamespace = "http://ws.gervajo.ita.oocl.com/", className = "com.oocl.ita.gervajo.ws.GetAnswer")
    @ResponseWrapper(localName = "getAnswerResponse", targetNamespace = "http://ws.gervajo.ita.oocl.com/", className = "com.oocl.ita.gervajo.ws.GetAnswerResponse")
    @Action(input = "http://ws.gervajo.ita.oocl.com/CalcCatalogue/getAnswerRequest", output = "http://ws.gervajo.ita.oocl.com/CalcCatalogue/getAnswerResponse")
    public double getAnswer(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
