
package com.oocl.ita.gervajo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcCatalogueService", targetNamespace = "http://ws.gervajo.ita.oocl.com/", wsdlLocation = "http://zha-ita129-w7:8080/MyWebService2/CalcCatalogueService?WSDL")
public class CalcCatalogueService
    extends Service
{

    private final static URL CALCCATALOGUESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCCATALOGUESERVICE_EXCEPTION;
    private final static QName CALCCATALOGUESERVICE_QNAME = new QName("http://ws.gervajo.ita.oocl.com/", "CalcCatalogueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita129-w7:8080/MyWebService2/CalcCatalogueService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCCATALOGUESERVICE_WSDL_LOCATION = url;
        CALCCATALOGUESERVICE_EXCEPTION = e;
    }

    public CalcCatalogueService() {
        super(__getWsdlLocation(), CALCCATALOGUESERVICE_QNAME);
    }

    public CalcCatalogueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCCATALOGUESERVICE_QNAME, features);
    }

    public CalcCatalogueService(URL wsdlLocation) {
        super(wsdlLocation, CALCCATALOGUESERVICE_QNAME);
    }

    public CalcCatalogueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCCATALOGUESERVICE_QNAME, features);
    }

    public CalcCatalogueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcCatalogueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcCatalogue
     */
    @WebEndpoint(name = "CalcCataloguePort")
    public CalcCatalogue getCalcCataloguePort() {
        return super.getPort(new QName("http://ws.gervajo.ita.oocl.com/", "CalcCataloguePort"), CalcCatalogue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcCatalogue
     */
    @WebEndpoint(name = "CalcCataloguePort")
    public CalcCatalogue getCalcCataloguePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gervajo.ita.oocl.com/", "CalcCataloguePort"), CalcCatalogue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCCATALOGUESERVICE_EXCEPTION!= null) {
            throw CALCCATALOGUESERVICE_EXCEPTION;
        }
        return CALCCATALOGUESERVICE_WSDL_LOCATION;
    }

}
