/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FireEvent.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 250,
                    width: 400,
                    bodyPadding: 10,
                    title: 'Button Clicking!',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.Msg.alert("Event", "Event Called");
                                Ext.getCmp('mybutton').hide();
                            },
                            draggable: true,
                            itemId: 'mybutton',
                            width: 95,
                            text: 'Click'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});