/*
 * File: app/view/Profile.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJS.view.Profile', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.button.Button'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'My Grid Panel',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ]
                },
                {
                    xtype: 'chart',
                    height: 250,
                    width: 400,
                    animate: true,
                    insetPadding: 20,
                    axes: [
                        {
                            type: 'Category',
                            fields: [
                                'x'
                            ],
                            position: 'left',
                            title: 'Category Axis'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'y'
                            ],
                            position: 'bottom',
                            title: 'Numeric Axis'
                        }
                    ],
                    series: [
                        {
                            type: 'bar',
                            label: {
                                display: 'insideEnd',
                                field: 'y',
                                color: '#333',
                                'text-anchor': 'middle'
                            },
                            axis: 'bottom',
                            xField: 'x',
                            yField: 'y'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    text: 'About Us',
                    tooltip: 'About Us',
                    tooltipType: 'title'
                }
            ]
        });

        me.callParent(arguments);
    }

});