/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DragAndDrop.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.container.Container',
        'Ext.Img'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 1000,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            width: 1000,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    height: 201,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5Cegypt.jpg'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 250,
                            width: 500,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'image',
                                    x: 270,
                                    y: 460,
                                    draggable: true,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5C5.png'
                                },
                                {
                                    xtype: 'image',
                                    x: 10,
                                    y: 460,
                                    draggable: true,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5C4.png'
                                },
                                {
                                    xtype: 'image',
                                    x: 270,
                                    y: 160,
                                    draggable: true,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5C3.png'
                                },
                                {
                                    xtype: 'image',
                                    x: 10,
                                    y: 160,
                                    draggable: true,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5C2.png'
                                },
                                {
                                    xtype: 'image',
                                    x: 140,
                                    y: 20,
                                    draggable: true,
                                    width: 201,
                                    src: '%5Capp%5Cimages%5C1.png'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});