
package com.oocl.ita.yapo.day17.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorApplicationService", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/", wsdlLocation = "http://zha-ita003-w7:7017/MyWebService/CalculatorApplicationService?wsdl")
public class CalculatorApplicationService
    extends Service
{

    private final static URL CALCULATORAPPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORAPPLICATIONSERVICE_EXCEPTION;
    private final static QName CALCULATORAPPLICATIONSERVICE_QNAME = new QName("http://webservice.day17.yapo.ita.oocl.com/", "CalculatorApplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita003-w7:7017/MyWebService/CalculatorApplicationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORAPPLICATIONSERVICE_WSDL_LOCATION = url;
        CALCULATORAPPLICATIONSERVICE_EXCEPTION = e;
    }

    public CalculatorApplicationService() {
        super(__getWsdlLocation(), CALCULATORAPPLICATIONSERVICE_QNAME);
    }

    public CalculatorApplicationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORAPPLICATIONSERVICE_QNAME, features);
    }

    public CalculatorApplicationService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORAPPLICATIONSERVICE_QNAME);
    }

    public CalculatorApplicationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORAPPLICATIONSERVICE_QNAME, features);
    }

    public CalculatorApplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorApplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorApplication
     */
    @WebEndpoint(name = "CalculatorApplicationPort")
    public CalculatorApplication getCalculatorApplicationPort() {
        return super.getPort(new QName("http://webservice.day17.yapo.ita.oocl.com/", "CalculatorApplicationPort"), CalculatorApplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorApplication
     */
    @WebEndpoint(name = "CalculatorApplicationPort")
    public CalculatorApplication getCalculatorApplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.day17.yapo.ita.oocl.com/", "CalculatorApplicationPort"), CalculatorApplication.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORAPPLICATIONSERVICE_EXCEPTION!= null) {
            throw CALCULATORAPPLICATIONSERVICE_EXCEPTION;
        }
        return CALCULATORAPPLICATIONSERVICE_WSDL_LOCATION;
    }

}
