
package com.oocl.ita.yapo.day17.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorApplication", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorApplication {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOperations", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/", className = "com.oocl.ita.yapo.day17.webservice.GetOperations")
    @ResponseWrapper(localName = "getOperationsResponse", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/", className = "com.oocl.ita.yapo.day17.webservice.GetOperationsResponse")
    @Action(input = "http://webservice.day17.yapo.ita.oocl.com/CalculatorApplication/getOperationsRequest", output = "http://webservice.day17.yapo.ita.oocl.com/CalculatorApplication/getOperationsResponse")
    public List<String> getOperations();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalculation", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/", className = "com.oocl.ita.yapo.day17.webservice.GetCalculation")
    @ResponseWrapper(localName = "getCalculationResponse", targetNamespace = "http://webservice.day17.yapo.ita.oocl.com/", className = "com.oocl.ita.yapo.day17.webservice.GetCalculationResponse")
    @Action(input = "http://webservice.day17.yapo.ita.oocl.com/CalculatorApplication/getCalculationRequest", output = "http://webservice.day17.yapo.ita.oocl.com/CalculatorApplication/getCalculationResponse")
    public double getCalculation(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
