/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.HomeController', {
    extend: 'Ext.app.Controller',

    control: {
        "#logBtn": {
            click: 'onLogBtnClick'
        },
        "#viewBtn": {
            click: 'onViewBtnClick'
        },
        "#loginBtn": {
            click: 'onLoginBtnClick'
        },
        "#homeBtn": {
            click: 'onHomeBtnClick'
        },
        "#kerberosBtn": {
            click: 'onKerberosBtnClick'
        },
        "#createBtn": {
            click: 'onCreateBtnClick'
        },
        "#aboutBtn": {
            click: 'onAboutBtnClick'
        },
        "#validateResetBtn": {
            click: 'onValidateResetBtnClick'
        },
        "#createResetBtn": {
            click: 'onCreateResetBtnClick'
        },
        "#registerBtn": {
            click: 'onRegisterBtnClick'
        },
        "#registerButton": {
            click: 'onRegisterButtonClick'
        }
    },

    onLogBtnClick: function(button, e, eOpts) {
                var username = Ext.getCmp('usernameTxt').getValue(); //get value of username
                var password = Ext.getCmp('passwordTxt').getValue(); // get value of password
                var loginView = Ext.getCmp('headerPanel');

                //TODO: Login using server-side authentication service
                Ext.Ajax.request({
                    url: 'login',
                    method: 'POST',
                    params:{
                        username:   username,
                        password:	password
                    },
                    callback: function(options, success, response) {

                         console.log(response);

                        if(response.responseText === 'false'){
                            --this.attempt;

                        } else if (response.responseText === 'true'){
                         formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");



                        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
                        var center = viewport.down('[region=center]');
                        var mainPanel = Ext.ComponentQuery.query('MyPanel')[0];

                        var view = Ext.create('MyPanel');

                        center.add(view);
                            Ext.getCmp('createBtn').hide();

                        }

                    },
                    failure : function(response) {

                        console.log("response", response);

                    }
                });

        Ext.getCmp('createBtn').hide();
    },

    onViewBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('viewBookingPanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(homePanel);
        center.remove(createPanel);
        center.add(view);
    },

    onLoginBtnClick: function(button, e, eOpts) {
        //var login = Ext.create('widget.loginform', {});

        // Show window
        //login.show();

        Ext.create('KerberosBooking.view.LoginForm').show();
    },

    onHomeBtnClick: function(button, e, eOpts) {
        // var viewport = Ext.ComponentQuery.query('mainViewport')[0],
        //     center = viewport.down('[region=center]'),
        //     viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
        //     homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
        //     createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        // 	//aboutPanel = Ext.ComponentQuery.query('')[0];

        //     view = Ext.create('MyPanel');

        // //console.log(viewport);

        // center.remove(viewPanel);
        // center.remove(homePanel);
        // center.remove(createPanel);
        // center.add(view);


        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
        var center = viewport.down('[region=center]'),
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];

        var view = Ext.create('myPanel');

        center.remove(homePanel);
        center.remove(createPanel);
        center.remove(viewPanel);
        center.add(view);
    },

    onKerberosBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('myHomePanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(createPanel);
        center.add(view);
    },

    onCreateBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('createBkgPanel');

        console.log(viewport);

        center.remove(mainPanel);
        center.remove(viewPanel);
        center.remove(homePanel);
        center.add(view);
    },

    onAboutBtnClick: function(button, e, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0],
            center = viewport.down('[region=center]'),
            mainPanel = Ext.ComponentQuery.query('MyPanel')[0],
            viewPanel = Ext.ComponentQuery.query('viewBookingPanel')[0],
            homePanel = Ext.ComponentQuery.query('myHomePanel')[0];
            createPanel = Ext.ComponentQuery.query('createBkgPanel')[0];
        	//aboutPanel = Ext.ComponentQuery.query('')[0];

            view = Ext.create('adminPanel');

        console.log(viewport);

        Ext.getCmp('homeToolbar').hide();

         center.remove(createPanel);
         center.remove(mainPanel);
         center.remove(viewPanel);
         center.remove(homePanel);
         center.add(view);


    },

    onValidateResetBtnClick: function(button, e, eOpts) {
          //var form = button.up('createBookingPanel'),
            var forms = button.up('form'),
         //values = form.getValues(),
              value = forms.getValues();
        var grid = Ext.getCmp('createContainer');
        //console.log(values);
        var containers = grid.getStore().data;
        //grid.getStore().data.items[0].data
        var arr = [];

        for (var i =0; i < containers.length; ++i){
            console.log(containers.items[i].data);
            arr.push(containers.items[i].data);
        }

        console.log(arr);
    },

    onCreateResetBtnClick: function(button, e, eOpts) {

    },

    onRegisterBtnClick: function(button, e, eOpts) {


        Ext.create('KerberosBooking.view.RegisterForm').show();
    },

    onRegisterButtonClick: function(button, e, eOpts) {
        var view = this.getView(),
            form = button.up('form'),
            formWindow = button.up('window'),
            values = form.getValues();


                console.log(values);
                 Ext.Msg.alert("Registration Success", "Your account will be checked and verified by the admin.");

                	// Close window
                    formWindow.destroy();
    }

});
