/*
 * File: app/model/AllBookingsModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.model.AllBookingsModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'shipmentNum'
        },
        {
            type: 'string',
            name: 'fromCity'
        },
        {
            type: 'string',
            name: 'toCity'
        },
        {
            type: 'string',
            name: 'fromDate'
        },
        {
            type: 'string',
            name: 'toDate'
        },
        {
            type: 'string',
            name: 'shipper'
        },
        {
            type: 'string',
            name: 'consignee'
        },
        {
            type: 'int',
            name: 'approveDoc'
        },
        {
            type: 'int',
            name: 'validWt'
        },
        {
            type: 'int',
            name: 'goodCustomer'
        },
        {
            type: 'string',
            name: 'shipmentStatus'
        },
        {
            type: 'string',
            name: 'createdBy'
        },
        {
            type: 'string',
            name: 'createDate'
        },
        {
            type: 'string',
            name: 'updateby'
        },
        {
            type: 'string',
            name: 'updateDate'
        }
    ]
});