/*
 * File: app/model/createBooking.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.model.AllBookingsModel', {
    extend: 'Ext.data.Model',
    alias: 'model.AllBookingsModel',
//    proxy: {
//        type: 'ajax',
//        url: 'contacts.json',
//        reader: {
//            type: 'json',
//            rootProperty: 'data'
//        }
//    },
    proxy: {
        type: 'ajax',
        url: 'getAllShipments',
        method: 'POST',
        extraParams:{
                username: localStorage.getItem('name'),
                jsonString: '{}'
        },
        reader: {
            type: 'json',
            idProperty: 'shipmentNum'
        },
        actionMethods: {
            create : 'POST',
            read   : 'POST', // by default GET
            update : 'POST',
            destroy: 'POST'
        }
    },
    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Field'
    ],
    hasMany: [
        {
            model: 'KerberosBooking.model.ShipmentContainer',
            associationKey: 'shipmentNum',
            getterName: 'shipmentNum',
            name: 'containers'
        }
    ],
    fields: [
        {
            type: 'int',
            name: 'shipmentNum'
        },
        {
            type: 'string',
            name: 'fromCity'
        },
        {
            type: 'string',
            name: 'toCity'
        },
        {
            type: 'string',
            name: 'fromDate'
        },
        {
            type: 'string',
            name: 'toDate'
        },
        {
            type: 'string',
            name: 'shipper'
        },
        {
            type: 'string',
            name: 'consignee'
        },
        {
            type: 'int',
            name: 'approveDoc'
        },
        {
            type: 'int',
            name: 'validWt'
        },
        {
            type: 'int',
            name: 'goodCustomer'
        },
        {
            type: 'string',
            name: 'shipmentStatus'
        },
        {
            type: 'string',
            name: 'createBy'
        },
        {
            type: 'string',
            name: 'createDate'
        },
        {
            type: 'string',
            name: 'updateby'
        },
        {
            type: 'string',
            name: 'updateDate'
        }
    ]
});