/*
 * File: app/model/createBooking.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.model.ShipmentContainer', {
    extend: 'Ext.data.Model',
    alias: 'model.ShipmentContainer',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Field'
    ],
    belongsTo: 'KerberosBooking.model.AllBookingsModel',
    fields: [
        {
            type: 'int',
            name: 'shipmentNum'
        },
        {
            type: 'string',
            name: 'fromCity'
        },
        {
            type: 'int',
            name: 'refNum'
        },
        {
            type: 'int',
            name: 'shipmentNum'
        },
        {
            type: 'string',
            name: 'cntrNum'
        },
        {
            type: 'int',
            name: 'grossWt'
        },
        {
            type: 'int',
            name: 'netWt'
        },
        {
            type: 'string',
            name: 'wtUnit'
        },
        {
            type: 'string',
            name: 'cntrType'
        },
    ]
});