CREATE TABLE SHP_CGO(
  CGO_ID VARCHAR2(5) NOT NULL PRIMARY KEY,
  CGO_DESC VARCHAR(100),
  CGO_NATURE VARCHAR(2),
  REF_NUM VARCHAR2(7),
  CONSTRAINT FK_REFNUM FOREIGN KEY (REF_NUM) REFERENCES SHP_CONTAINER(REF_NUM)
);

COMMIT;

select * from SHP_CGO;