CREATE TABLE SHP_CONTAINER(
  REF_NUM NUMBER(7) NOT NULL PRIMARY KEY,
  CNTR_NUM VARCHAR2(20),
  GROSS_WT NUMBER(12,3),
  NET_WT NUMBER(12,3),
  WT_UNIT VARCHAR2(10)
);

CREATE SEQUENCE REF_NUM_SEQ
START WITH 1000000
INCREMENT BY 1
NOCYCLE
CACHE 10;