CREATE TABLE SHP_SHIPMENT(
  SHIPMENT_NUM VARCHAR2(10) NOT NULL PRIMARY KEY,
  FROM_CITY VARCHAR2(50),
  TO_CITY VARCHAR2(50),
  FROM_DATE DATE,
  DATE_TO DATE,
  SHIPPER VARCHAR2(255),
  CONSIGNEE VARCHAR2(255),
  APPROVE_DOC NUMBER(1),
  VALID_WT NUMBER(1),
  GOOD_CUSTOMER NUMBER(1),
  SHIPMENT_STATUS VARCHAR2(20),
  CREATE_BY VARCHAR2(255),
  CREATE_DATE DATE,
  UPDATE_BY VARCHAR2(255),
  UPDATE_DATE DATE
);

CREATE SEQUENCE SHIPMENT_NUM
START WITH 4000000000
INCREMENT BY 10
NOCYCLE
CACHE 10;