/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DragAndDrop.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'DragAndDrop.view.MyViewportViewModel',
        'Ext.Img'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'absolute',

    items: [
        {
            xtype: 'image',
            x: 70,
            y: 30,
            draggable: true,
            height: 201,
            width: 610,
            src: '%5Capp%5Cimages%5C5.png'
        },
        {
            xtype: 'image',
            x: 60,
            y: 550,
            draggable: true,
            height: 201,
            width: 610,
            src: '%5Capp%5Cimages%5C7.png'
        },
        {
            xtype: 'image',
            x: 70,
            y: 280,
            draggable: true,
            height: 201,
            width: 620,
            src: '%5Capp%5Cimages%5C6.png'
        }
    ]

});