/*
 * File: app/store/MyStore1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyStore1', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.MyModel1'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.MyModel1',
            storeId: 'MyStore1',
            data: [
                {
                    firstName: 'Russell',
                    lastName: 'Rodriguez',
                    age: '20',
                    address: 'Philippines'
                },
                {
                    firstName: 'May',
                    lastName: 'Cook',
                    age: '22',
                    address: 'New York'
                },
                {
                    firstName: 'Homer',
                    lastName: 'Jones',
                    age: '21',
                    address: 'China'
                },
                {
                    firstName: 'Ada',
                    lastName: 'Nelson',
                    age: '26',
                    address: 'Japan'
                },
                {
                    firstName: 'Martin',
                    lastName: 'Nguyen',
                    age: '24',
                    address: 'Texas'
                }
            ]
        }, cfg)]);
    }
});