
package net.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyCalculator", targetNamespace = "http://webservice.sw1.bituiga.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyCalculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateThis", targetNamespace = "http://webservice.sw1.bituiga.oocl.com/", className = "com.oocl.bituiga.sw1.webservice.CalculateThis")
    @ResponseWrapper(localName = "calculateThisResponse", targetNamespace = "http://webservice.sw1.bituiga.oocl.com/", className = "com.oocl.bituiga.sw1.webservice.CalculateThisResponse")
    @Action(input = "http://webservice.sw1.bituiga.oocl.com/MyCalculator/calculateThisRequest", output = "http://webservice.sw1.bituiga.oocl.com/MyCalculator/calculateThisResponse")
    public Double calculateThis(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
