/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DragNDrop.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'DragNDrop.view.MyViewportViewModel',
        'Ext.Img'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'absolute',

    items: [
        {
            xtype: 'image',
            x: 490,
            y: -38,
            height: 680,
            width: 550,
            src: '%5Capp%5Cimages%5CEditing-Rectangle-icon.png'
        },
        {
            xtype: 'image',
            x: 0,
            y: -37,
            height: 680,
            width: 550,
            src: '%5Capp%5Cimages%5CEditing-Rectangle-icon.png'
        },
        {
            xtype: 'image',
            x: 30,
            y: 70,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        },
        {
            xtype: 'image',
            x: 200,
            y: 70,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        },
        {
            xtype: 'image',
            x: 200,
            y: 230,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        },
        {
            xtype: 'image',
            x: 200,
            y: 380,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        },
        {
            xtype: 'image',
            x: 30,
            y: 380,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        },
        {
            xtype: 'image',
            x: 30,
            y: 230,
            draggable: true,
            height: 150,
            width: 150,
            src: '%5Capp%5Cimages%5Cgiphy.gif'
        }
    ]

});