/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DragDropSW.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.Img'
    ],

    layout: 'column',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 790,
                    itemId: 'mypanel',
                    width: 1301,
                    layout: 'absolute',
                    simpleDrag: true,
                    titleCollapse: true,
                    items: [
                        {
                            xtype: 'image',
                            x: 340,
                            y: 70,
                            draggable: true,
                            height: 210,
                            itemId: 'myimg',
                            width: 170,
                            src: '%5Capp%5Cimages%5Cgiraffe.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 320,
                            y: 320,
                            draggable: true,
                            height: 190,
                            width: 220,
                            src: '%5Capp%5Cimages%5Crabbit.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 70,
                            y: 210,
                            draggable: true,
                            height: 180,
                            width: 230,
                            src: '%5Capp%5Cimages%5Celephant.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 80,
                            y: 410,
                            draggable: true,
                            height: 200,
                            width: 190,
                            src: '%5Capp%5Cimages%5Ccat.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 80,
                            y: 20,
                            draggable: true,
                            height: 160,
                            width: 190,
                            src: '%5Capp%5Cimages%5Cbear.jpg'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});