/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Label',
        'Ext.Img'
    ],

    id: 'homeViewport',
    itemId: 'homeViewport',
    style: 'background:transparent;',
    autoScroll: true,
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    autoScroll: true,
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            height: 35,
                            items: [
                                {
                                    xtype: 'button',
                                    margin: 10,
                                    padding: 0,
                                    style: 'background:transparent;border: none;',
                                    text: 'Home',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                id: 'gridId',
                                                itemId: 'gridId',
                                                text: 'Get The Grid'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'graphId',
                                                itemId: 'graphId',
                                                text: 'Graphs and Window'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    padding: 0,
                                    style: 'background:transparent;border: none;',
                                    text: 'About'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 195,
                            padding: '20px',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<b><i><font size= 20px><h1>The Thousand Island Kingdom</h1></i></b></font>'
                                },
                                {
                                    xtype: 'label',
                                    html: '<i>Wild wind is billowing and is harsh against my face. The day has come for me to end my journey through mountains and rock. Across the vast land is the castle I once lived, the castle I once had. Anger shot through me as I imagined the life of those who tried to crush mine, inside of the castle. They’ve must live so happily and comfortably, I thought, while I trudge on an abandoned wasteland, alone. I am tired and cold and hungry, but my hunger for revenge is more powerful. With a tired sigh, I took out the letter my mother gave to me on my 18th birthday, the last day I saw her alive, and read it once more.</i>',
                                    text: ''
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            border: 10,
                            height: 283,
                            padding: 10,
                            style: 'background:transparent;border: none;',
                            layout: {
                                type: 'border',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    region: 'west',
                                    padding: 10,
                                    style: 'background:transparent;border: none;',
                                    width: 150,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'image',
                                            flex: 1,
                                            region: 'center',
                                            src: '%5Capp%5Cimages%5Caurora.jpg',
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onImageAfterRender,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    region: 'center',
                                    padding: 10,
                                    style: 'background:transparent;border: none;',
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'image',
                                            region: 'center',
                                            src: '%5Capp%5Cimages%5Cclouds.gif',
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onImageAfterRender1,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    region: 'east',
                                    padding: 10,
                                    style: 'background:transparent;border: none;',
                                    width: 150,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'image',
                                            region: 'center',
                                            src: '%5Capp%5Cimages%5Cforest.jpg',
                                            listeners: {
                                                afterrender: {
                                                    fn: me.onImageAfterRender2,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onImageAfterRender: function(component, eOpts) {
        Ext.create('Ext.tip.ToolTip', {
                            target: component.getEl(),
                            html: 'This is image 1'
                        });
    },

    onImageAfterRender1: function(component, eOpts) {
        Ext.create('Ext.tip.ToolTip', {
                            target: component.getEl(),
                            html: 'This is image 2'
                        });
    },

    onImageAfterRender2: function(component, eOpts) {
        Ext.create('Ext.tip.ToolTip', {
                            target: component.getEl(),
                            html: 'This is image 3'
                        });
    }

});