/*
 * File: app/view/MyViewport1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport1', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Spacer',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    id: 'gridViewport',
    itemId: 'gridViewport',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'gridPanelId',
                    itemId: 'gridPanelId',
                    title: '',
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    margin: 10,
                                    style: 'background:transparent;border: none;',
                                    text: 'Home',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                id: 'homeId',
                                                itemId: 'homeId',
                                                text: 'Home Page'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'graphId2',
                                                itemId: 'graphId2',
                                                text: 'Graphs and Window'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    style: 'background:transparent;border: none;',
                                    text: 'About'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            id: 'userForm',
                            itemId: 'userForm',
                            layout: 'absolute',
                            bodyPadding: 10,
                            titleCollapse: true,
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    x: 10,
                                    y: 20,
                                    id: 'firstName',
                                    itemId: 'firstName',
                                    width: 722,
                                    fieldLabel: 'First Name'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    x: 10,
                                    y: 50,
                                    id: 'lastName',
                                    itemId: 'lastName',
                                    fieldLabel: 'Last Name'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    x: 10,
                                    y: 80,
                                    id: 'age',
                                    itemId: 'age',
                                    fieldLabel: 'Age'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    x: 10,
                                    y: 110,
                                    id: 'address',
                                    itemId: 'address',
                                    fieldLabel: 'Address'
                                },
                                {
                                    xtype: 'button',
                                    x: 650,
                                    y: 150,
                                    id: 'submitBtn',
                                    itemId: 'submitBtn',
                                    text: 'Submit',
                                    listeners: {
                                        click: {
                                            fn: me.onSubmitBtnClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'button',
                                    x: 560,
                                    y: 150,
                                    text: 'See a message',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            id: 'userList',
                            itemId: 'userList',
                            title: 'User List',
                            store: 'MyStore1',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'firstName',
                                    text: 'First Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'lastName',
                                    text: 'Last Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'age',
                                    text: 'Age'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'address',
                                    text: 'Address'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onSubmitBtnClick: function(button, e, eOpts) {
         var iForm = Ext.getCmp('userForm'),
                iValues = iForm.getValues(),
             iStore = Ext.getCmp('userList').getStore();



        iStore.add(iValues);

        console.log(iValues);

        Ext.getCmp('userList').getView().refresh();
    },

    onButtonClick: function(button, e, eOpts) {
        var msg = Ext.create('Ext.window.MessageBox');

        msg.alert('An Exerpt from the Late Queens Letter', 'Surrounded by an endlessly pallid expanse of pulverized skeletons, I watched you grow strong and proud and terrifyingly beautiful, a queen of a lonesome kingdom whose only subjects were the ghosts that wailed on the wind.');
    }

});