
package com.oocl.licupca.misc.ws.main;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcuMainService", targetNamespace = "http://main.ws.misc.licupca.oocl.com/", wsdlLocation = "http://zha-ita066-w7:8080/LICUPCA22AUG/CalcuMainService?wsdl")
public class CalcuMainService
    extends Service
{

    private final static URL CALCUMAINSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCUMAINSERVICE_EXCEPTION;
    private final static QName CALCUMAINSERVICE_QNAME = new QName("http://main.ws.misc.licupca.oocl.com/", "CalcuMainService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita066-w7:8080/LICUPCA22AUG/CalcuMainService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCUMAINSERVICE_WSDL_LOCATION = url;
        CALCUMAINSERVICE_EXCEPTION = e;
    }

    public CalcuMainService() {
        super(__getWsdlLocation(), CALCUMAINSERVICE_QNAME);
    }

    public CalcuMainService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCUMAINSERVICE_QNAME, features);
    }

    public CalcuMainService(URL wsdlLocation) {
        super(wsdlLocation, CALCUMAINSERVICE_QNAME);
    }

    public CalcuMainService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCUMAINSERVICE_QNAME, features);
    }

    public CalcuMainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcuMainService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcuMain
     */
    @WebEndpoint(name = "CalcuMainPort")
    public CalcuMain getCalcuMainPort() {
        return super.getPort(new QName("http://main.ws.misc.licupca.oocl.com/", "CalcuMainPort"), CalcuMain.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcuMain
     */
    @WebEndpoint(name = "CalcuMainPort")
    public CalcuMain getCalcuMainPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.ws.misc.licupca.oocl.com/", "CalcuMainPort"), CalcuMain.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCUMAINSERVICE_EXCEPTION!= null) {
            throw CALCUMAINSERVICE_EXCEPTION;
        }
        return CALCUMAINSERVICE_WSDL_LOCATION;
    }

}
