
package com.oocl.licupca.misc.ws.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcuMain", targetNamespace = "http://main.ws.misc.licupca.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcuMain {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://main.ws.misc.licupca.oocl.com/", className = "com.oocl.licupca.misc.ws.main.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://main.ws.misc.licupca.oocl.com/", className = "com.oocl.licupca.misc.ws.main.CalculateResponse")
    @Action(input = "http://main.ws.misc.licupca.oocl.com/CalcuMain/calculateRequest", output = "http://main.ws.misc.licupca.oocl.com/CalcuMain/calculateResponse")
    public double calculate(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
