/*
 * File: app/view/MyViewport2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport2', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Label',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    id: 'graphViewportID',
    itemId: 'graphViewportID',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    titleCollapse: true,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    margin: 10,
                                    style: 'background:transparent;border: none;',
                                    text: 'Home',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                id: 'homeId2',
                                                text: 'Home Page'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                id: 'gridId2',
                                                text: 'Grid Page'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    style: 'background:transparent;border: none;',
                                    text: 'About'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            padding: 15,
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<i><h3>To my darling princess,</h3></i>',
                                    text: ''
                                },
                                {
                                    xtype: 'label',
                                    height: 0,
                                    html: '<i><p>Today is a special day. It is you 18th birthday and your day of liberation. I wish you could have spent this birthday as the girl I always dreamed you would be—the girl you always deserved to be—and not lost among the vast dead land and musty waters, blown by the winds and crushed under the feet of dying wanderers. I wish I could still be at your side. But things are about to change, my love. I still remember the day of your birth as the greatest day of my life. It was during a whimsical spring twilight, one of those nights where the sapphire skies drip with sweet, little, glittering raindrops; where the all other fairies and pixies flitter from place to place, giving life to the living creatures that we rule over. I was the young and immortal fairy queen, with pale and shimmering skin that reflects the moonlight and dark orbs that sees all. In those days, I knew very little about the world, having only emerged a year before from my hidden palace on the mountains, to be married to the Sun King, the dark haired Datu of the mortal land, king of the Kingdom of Thousand Islands.</p></i>'
                                },
                                {
                                    xtype: 'button',
                                    id: 'readBtn',
                                    itemId: 'readBtn',
                                    text: 'Read More'
                                }
                            ]
                        },
                        {
                            xtype: 'chart',
                            flex: 1,
                            height: 250,
                            width: 400,
                            animate: true,
                            insetPadding: 20,
                            store: 'MyStore',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'name'
                                    ],
                                    title: 'Category Axis',
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'value'
                                    ],
                                    title: 'Numeric Axis',
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    xField: 'name',
                                    yField: 'value',
                                    smooth: 3
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});