/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Label'
    ],

    height: 304,
    width: 568,
    title: 'My Window',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 191,
                            title: 'Tab 1',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<i><p>Our marriage was a political one to unify the Enchanted Beings and the Human kingdom, but from there emerged a deep understanding and love between me and your glorious father. Your arrival cemented our marriage; for having an heir to the kingdom meant that the unified bloodline will live. Precious soul, you were enchanting as you are dangerous. Your pearlescent skin akin to mine glowed faintly, your dark brown eyes like your father’s were huge and calculating; your raven hair was floating, like you were constantly submerged on the fours seas. It was the only indication of how powerful you are, my daughter, for only the union of the most hazardous queen and the most violent and mighty king could produce such a dangerous weapon. Yet there was nothing to me more precious in the world than my little one. How I adored you. Your father was elated, for he now has a heir to the throne of his kingdom. Your mere presence in court was commanding and explosive, with violent outburst of power and rage, scaring the humans that served your father for years. But you were young; I understood that great power is hard to control. But others did not, for you pose a threat to their plan.  </i></p>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 2',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<i><p>One of them was the Serpentine Warrior, your uncle with eyes like snakes, the blood-lusted brother of the formidable Sun King. An heir would only mean that he would never have the throne he coveted. You were a threat, but he cannot kill you for I knew of his plan and protected you from the scheming and cunning threats of our enemies. So he formulated a way for us to be ruined and displaced. A few whispered lies here and there; A few bribes for witnesses and naysayers; A few years of letting the lies spread throughout the kingdoms. Soon, everyone knows of how I, the fairy queen, tricked your father into believing that you were his child. To them, I used my dark magic to weave and change his memories into believing that you were his. To them, you were not the heir of the kingdom but an illegitimate daughter of the queen; the begotten child of your father’s rival, the Warlock of the South, the great Datu of the Seas.</i></p>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<i><p>The rumors were spreading like wildfire and were vicious. I tried to protect you from it, but the court was always a place of intrigue and scheming, for no one ever supported the union of an enchanted being to that of a human. The Serpentine Warrior whispered more cruel lies to the Sun King, with each word dripping in poison. Your father believed him, no matter how much I beg and reasoned with him. He was his brother after all, and I was a fairy, who only lived in his palace for a few years, who never belonged to interact with mortals. As punishment from my supposed infidelity, he married his brother’s daughter, the Jade Princess, with her oriental features from the land across the vast ocean, and banished us to an isolated obsidian tower in near the Abysmal Sea. The Abysmal Sea, out of all the four seas that surround and nurture the kingdom, is the most thunderous, the emptiest of souls, and the most fearsome. Surrounded by miles and miles of inhabitable land, this sea gave no life, but only death in the most agonizing way. Thunderstorms and typhoons visit with frequency, destroying all traces of civilization that has tried to stay in this land. There are only the ruins of cities, remains of roads, bones of the hallowed dead. There are so many bones, piling up after eons of wars, which the brutal sunshine has dissolved them all into a vast expanse of shining white sand dunes and is slowly eaten away by the turbulent waters.</p></i>'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});