/*
 * File: app/view/createPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.createPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.createPanel',

    alternateClassName: [
        'createPanel'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    id: 'createPanel',
    itemId: 'createPanel',
    scrollable: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'form',
                    id: 'kerberosCreatePanel',
                    itemId: 'kerberosCreatePanel',
                    bodyPadding: 10,
                    title: 'Create Booking',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    width: 343,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Booking Number',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'From City',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'From Date',
                                            labelWidth: 120
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Container Number',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'To City',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'To Date',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'toolbar',
                                            padding: '',
                                            layout: {
                                                type: 'hbox',
                                                padding: 5
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbfill',
                                                    flex: 1,
                                                    width: 235
                                                },
                                                {
                                                    xtype: 'button',
                                                    dock: 'right',
                                                    style: {
                                                        background: '#FFFFFF'
                                                    },
                                                    scale: 'medium',
                                                    text: 'Submit'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});