/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Label',
        'Ext.Img',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    id: 'mainView',
    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'center',
                    id: 'headerPanel',
                    itemId: 'headerPanel',
                    autoScroll: true,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'usernameTxt',
                                            fieldLabel: 'Username:'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'passwordTxt',
                                            fieldLabel: 'Password:',
                                            inputType: 'password'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Remember Me?',
                                            boxLabel: ''
                                        },
                                        {
                                            xtype: 'container',
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'toolbar',
                                                    items: [
                                                        {
                                                            xtype: 'tbfill',
                                                            width: 50
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            id: 'signInBtn',
                                                            itemId: 'signInBtn',
                                                            text: 'Sign In'
                                                        },
                                                        {
                                                            xtype: 'tbfill',
                                                            width: 50
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            id: 'createAccBtn',
                                                            itemId: 'createAccBtn',
                                                            text: 'Create Account'
                                                        },
                                                        {
                                                            xtype: 'tbfill'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    html: '<i><center>Forgot Password?</center></i>'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'image',
                                    flex: 1,
                                    height: 146,
                                    width: 1038,
                                    src: '%5Cimages%5CKerberosBanner.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'north',
                    height: '100%',
                    hidden: true,
                    id: 'bookingPanel',
                    itemId: 'bookingPanel',
                    autoScroll: true,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: '',
                            itemId: '',
                            width: 360,
                            items: [
                                {
                                    xtype: 'image',
                                    flex: 1,
                                    height: 73,
                                    width: 560,
                                    src: '%5Cimages%5CKerberosBanner.jpg'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'label',
                                    text: 'Username:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'user',
                                    itemId: 'user',
                                    text: 'My Label'
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            dock: 'top',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Search Booking'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Create Booking'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Manage Users'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});