/*
 * File: app/view/myTabKer.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.myTabKer', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.myTabKer',

    alternateClassName: [
        'myTabKer'
    ],
    requires: [
        'Ext.panel.Panel',
        'Ext.tab.Tab',
        'Ext.tab.Bar'
    ],

    viewModel: {
        type: 'mytabker'
    },
    border: false,
    flex: 1,
    id: 'myTabKer',
    itemId: 'myTabKer',
    margin: '0 0 0 0',
    defaults: {
        tabConfig: {
            responsiveConfig: {
                wide: {
                    iconAlign: 'left',
                    textAlign: 'left',
                    flex: 0
                },
                tall: {
                    iconAlign: 'top',
                    textAlign: 'center',
                    flex: 1
                }
            },
            plugins: 'responsive'
        }
    },
    animCollapse: true,
    collapseDirection: 'right',
    collapsible: true,
    frameHeader: false,
    header: {
        layout: {
            align: 'stretchmax'
        },
        iconCls: 'exec-header-icon',
        title: {
            textAlign: 'center',
            flex: 0,
            minWidth: 0
        }
    },
    headerPosition: 'left',
    title: '<strong>Hello</strong>',
    titleCollapse: false,
    titleRotation: 0,
    activeTab: 0,
    tabBarHeaderPosition: 1,
    tabRotation: 0,

    items: [
        {
            xtype: 'panel',
            flex: 1,
            title: 'Bookings',
            tabConfig: {
                xtype: 'tab',
                flex: 1,
                flex: 1,
                margin: '0 0 0 0',
                width: 178
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            animCollapse: true,
            title: 'Tab 2',
            tabConfig: {
                xtype: 'tab',
                flex: 1,
                margin: '0 0 0 0'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            title: 'Tab 3',
            tabConfig: {
                xtype: 'tab',
                flex: 1,
                margin: '0 0 0 0'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            margin: 0,
            padding: 0,
            title: 'Tab 3',
            tabConfig: {
                xtype: 'tab',
                flex: 1,
                margin: '0 0 0 0'
            }
        }
    ],
    tabBar: {
        xtype: 'tabbar',
        flex: 1,
        padding: 0
    }

});