/*
 * File: app/view/MyContainer2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer2', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.form.Label'
    ],

    height: 397,
    width: 613,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    x: 270,
                    y: 70,
                    height: 30,
                    width: 120,
                    text: 'PAGE 2'
                }
            ]
        });

        me.callParent(arguments);
    }

});