/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.button.Button',
        'Ext.form.Label'
    ],

    height: 397,
    width: 613,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    x: 150,
                    y: 140,
                    text: 'Go to Page 1',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                me.processGotoPage2({
                    xtype: 'button',
                    x: 370,
                    y: 140,
                    text: 'Go to Page 2',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                }),
                {
                    xtype: 'label',
                    x: 270,
                    y: 70,
                    height: 30,
                    width: 120,
                    text: 'HOME PAGE'
                }
            ]
        });

        me.callParent(arguments);
    },

    processGotoPage2: function(config) {
        return config;
    },

    onButtonClick: function(button, e, eOpts) {

    },

    onButtonClick1: function(button, e, eOpts) {

    },

    callPage1: function() {

    }

});