/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.Account', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'bookingPanel',
            selector: '#bookingPanel'
        },
        {
            ref: 'headerPanel',
            selector: '#headerPanel'
        }
    ],

    showRegister: function(target) {

        // Create new register form window
        var register = Ext.create("widget.registerform");

        // Show window
        register.show();

    },

    doRegister: function(button, e, eOpts) {

        var form = button.up('form'),				// Register form
            formWindow = button.up('window'),		// Register form window
            values = form.getValues();				// Form values
           	// Panel shown when logged in

        // Success

        console.log(values);
        var successCallback = function(resp, ops) {
         Ext.Msg.alert("Registration Success", "Your account will be checked and verified by the admin.");

        	// Close window
            formWindow.destroy();

        };

        // Failure
        var failureCallback = function(resp, ops) {

            // Show registration failure error
            Ext.Msg.alert("Registration Failure", resp);

        };


        // TODO: Register using server-side registration service
        // Ext.Ajax.request({
        //		url: "/register",
        //		params: values,
        //		success: successCallback,
        //		failure: failureCallback
        // });

        successCallback();

    },

    onCreateAccBtnClick: function(button, e, eOpts) {

        var register = Ext.create("widget.registerform");


        register.show();
    },

    onSignInBtnClick: function(button, e, eOpts) {

        var username = Ext.getCmp('usernameTxt').getValue(); //get value of username
        var password = Ext.getCmp('passwordTxt').getValue(); // get value of password
        var loginView = Ext.getCmp('headerPanel');


        //TODO: Login using server-side authentication service
        Ext.Ajax.request({
            url: '/login',
            method: 'POST',
            params:{
                username:   username,
                password:	passowrd
            },
            callback: function(options, success, response) {
                var rec=Ext.decode(response.responseText);
                console.log(rec);
                Ext.Msg.alert("Login Success", "Logged In");

            },
            failure : function(response) {

                console.log("response", response);
                if(this.attempt !==0){
                    --this.attempt;
                Ext.Msg.alert("Login Failure", "Wrong Username or Password");

            } else{
                Ext.Msg.alert("Login Failure", "Blocked1! Please contact Admin");
            }
            }
        });


        console.log(this.attempt); //checking of global variable






    },

    init: function(application) {
                this.attempt =3;

        this.control({
            "mainview #registerButton": {
                click: this.showRegister
            },
            "registerform #registerButton": {
                click: this.doRegister
            },
            "#createAccBtn": {
                click: this.onCreateAccBtnClick
            },
            "#signInBtn": {
                click: this.onSignInBtnClick
            }
        });
    }

});
