/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.controller.HomeController', {
    extend: 'Ext.app.Controller',

    control: {
        "#logBtn": {
            click: 'onLogBtnClick'
        },
        "#kerberosBtn": {
            click: 'onKerberosBtnClick'
        },
        "#viewBtn": {
            click: 'onViewBtnClick'
        },
        "#loginBtn": {
            click: 'onLoginBtnClick'
        }
    },

    onLogBtnClick: function(button, e, eOpts) {
                var username = Ext.getCmp('usernameTxt').getValue(); //get value of username
                var password = Ext.getCmp('passwordTxt').getValue(); // get value of password
                var loginView = Ext.getCmp('headerPanel');

                //TODO: Login using server-side authentication service
                Ext.Ajax.request({
                    url: 'login',
                    method: 'POST',
                    params:{
                        username:   username,
                        password:	passowrd
                    },
                    callback: function(options, success, response) {

                         console.log(response);

                        if(response.responseText === 'false'){
                            --this.attempt;

                        } else if (response.responseText === 'true'){
                         formWindow.destroy();
                            Ext.Msg.alert("Login Success", "Logged In");



                        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
                        var center = viewport.down('[region=center]');
                        var mainPanel = Ext.ComponentQuery.query('MyPanel')[0];

                        var view = Ext.create('MyPanel');

                        center.add(view);
                            Ext.getCmp('createBtn').hide();

                        }

                    },
                    failure : function(response) {

                        console.log("response", response);

                    }
                });

        Ext.getCmp('createBtn').hide();
    },

    onKerberosBtnClick: function(button, e, eOpts) {

    },

    onViewBtnClick: function(button, e, eOpts) {
        console.log('view');
        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
                                var center = viewport.down('[region=center]');
                                var mainPanel = Ext.ComponentQuery.query('MyPanel')[0];

                                var view = Ext.create('kerberosPanel');

                                center.remove(mainPanel);
                                center.add(view);
    },

    onLoginBtnClick: function(button, e, eOpts) {
        //var login = Ext.create('widget.loginform', {});

        // Show window
        //login.show();

        Ext.create('KerberosBooking.view.LoginForm').show();
    }

});
