/*
 * File: app/view/createBkgPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.createBkgPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.createBkgPanel',

    alternateClassName: [
        'createBkgPanel'
    ],
    requires: [
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CheckboxModel',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Fill'
    ],

    id: 'createBkgPanel',
    itemId: 'createBkgPanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 900,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    dock: 'top',
                    flex: 1,
                    height: 201,
                    hidden: true,
                    width: 201,
                    src: '%5Cimages%5Cbg%5Cenglishmap.jpg'
                }
            ],
            listeners: {
                afterrender: 'onContainerAfterRender'
            }
        },
        {
            xtype: 'container',
            scrollable: true,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    id: 'createBookingPanel',
                    itemId: 'createBookingPanel',
                    layout: 'auto',
                    bodyPadding: 10,
                    title: 'Create Booking',
                    titleAlign: 'left',
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            id: 'bookingPanel',
                            itemId: 'bookingPanel',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    disabled: true,
                                    id: 'bookingNumber',
                                    itemId: 'bookingNumber',
                                    padding: 10,
                                    fieldLabel: 'Booking Number',
                                    name: 'shipmentNumber',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    id: 'bookingOffice',
                                    itemId: 'bookingOffice',
                                    padding: 10,
                                    fieldLabel: 'Booking Office',
                                    name: 'bookingOffice',
                                    allowBlank: false,
                                    validateBlank: true,
                                    store: [
                                        'MNL',
                                        'HKG',
                                        'ZHA',
                                        'USA'
                                    ]
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '',
                                    padding: 10,
                                    width: 147,
                                    text: 'Booking Status'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: '<span style="color:red;font-weight:bold">Pending</span>',
                                    padding: 10,
                                    width: 147
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            id: 'bookingInfoPanel',
                            itemId: 'bookingInfoPanel',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'bookingShipper',
                                            itemId: 'bookingShipper',
                                            padding: 10,
                                            fieldLabel: 'Shipper',
                                            labelWidth: 120,
                                            name: 'shipper',
                                            allowBlank: false,
                                            validateBlank: true
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'fromdate',
                                            itemId: 'fromdate',
                                            padding: 10,
                                            fieldLabel: 'From Date',
                                            labelWidth: 120,
                                            name: 'fromDate',
                                            allowBlank: false,
                                            validateBlank: true,
                                            format: 'Y-m-d',
                                            listeners: {
                                                blur: 'onFromdateBlur'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'bookingConsignee',
                                            itemId: 'bookingConsignee',
                                            padding: 10,
                                            fieldLabel: 'Consignee',
                                            labelWidth: 120,
                                            name: 'consignee',
                                            allowBlank: false,
                                            validateBlank: true
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'toDate',
                                            itemId: 'toDate',
                                            padding: 10,
                                            fieldLabel: 'To Date',
                                            labelWidth: 120,
                                            name: 'toDate',
                                            allowBlank: false,
                                            validateBlank: true,
                                            format: 'Y-m-d',
                                            listeners: {
                                                blur: 'onToDateBlur'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'containerPanel',
                            itemId: 'containerPanel',
                            padding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    id: 'bookingFromCity',
                                                    itemId: 'bookingFromCity',
                                                    padding: 10,
                                                    fieldLabel: 'From City',
                                                    labelWidth: 120,
                                                    name: 'fromCity',
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    validateBlank: true,
                                                    store: [
                                                        'HKG',
                                                        'LGB',
                                                        'MNL',
                                                        'SIN',
                                                        'PUS',
                                                        'RTM'
                                                    ],
                                                    listeners: {
                                                        blur: 'onBookingFromCityBlur'
                                                    }
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'bookingCargoNature',
                                                    itemId: 'bookingCargoNature',
                                                    padding: 10,
                                                    fieldLabel: 'Cargo Nature',
                                                    labelWidth: 120,
                                                    name: 'cargoNature',
                                                    allowBlank: false,
                                                    validateBlank: true,
                                                    store: [
                                                        'GC',
                                                        'RF',
                                                        'AWK',
                                                        'DG'
                                                    ]
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'bookingCargoDesc',
                                                    itemId: 'bookingCargoDesc',
                                                    padding: 10,
                                                    fieldLabel: 'Cargo Description',
                                                    labelWidth: 120,
                                                    name: 'cargoDesc',
                                                    allowBlank: false,
                                                    validateBlank: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            padding: '',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    id: 'bookingToCity',
                                                    itemId: 'bookingToCity',
                                                    padding: 10,
                                                    fieldLabel: 'To City',
                                                    labelWidth: 120,
                                                    name: 'toCity',
                                                    allowBlank: false,
                                                    validateBlank: true,
                                                    store: [
                                                        'HKG',
                                                        'LGB',
                                                        'MNL',
                                                        'SIN',
                                                        'PUS',
                                                        'RTM'
                                                    ],
                                                    listeners: {
                                                        blur: 'onBookingToCityBlur'
                                                    }
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    id: 'bookingConHS',
                                                    itemId: 'bookingConHS',
                                                    padding: 10,
                                                    fieldLabel: 'HS Code',
                                                    labelWidth: 120,
                                                    name: 'containerHS',
                                                    allowBlank: false,
                                                    validateBlank: true,
                                                    store: [
                                                        'MNL',
                                                        'HKG',
                                                        'ZHA',
                                                        'USA'
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            height: 177,
                                            id: 'createContainer',
                                            itemId: 'createContainer',
                                            resizable: true,
                                            title: '',
                                            store: 'createBooking',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            id: 'addCntr',
                                                            itemId: 'addCntr',
                                                            text: 'Add'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            id: 'deleteCntr',
                                                            itemId: 'deleteCntr',
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            id: 'copyCntr',
                                                            itemId: 'copyCntr',
                                                            text: 'Copy'
                                                        }
                                                    ]
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    id: 'bookingConRef',
                                                    itemId: 'bookingConRef',
                                                    dataIndex: 'referenceNumber',
                                                    text: 'Reference Number'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'containerNumber',
                                                    flex: 1,
                                                    id: 'bookingConNumber',
                                                    itemId: 'bookingConNumber',
                                                    text: 'Container Number',
                                                    editor: {
                                                        xtype: 'combobox',
                                                        name: 'cntrType',
                                                        allowBlank: false,
                                                        validateBlank: true,
                                                        store: [
                                                            '20GP',
                                                            '40GP',
                                                            '20HQ',
                                                            '40HQ',
                                                            '4HQ'
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    dataIndex: 'grossWeight',
                                                    text: 'Gross Weight',
                                                    editor: {
                                                        xtype: 'textfield',
                                                        id: 'grossWt',
                                                        itemId: 'grossWt',
                                                        name: 'grossWt',
                                                        allowBlank: false,
                                                        validateBlank: true
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    dataIndex: 'netWeight',
                                                    text: 'Net Weight',
                                                    editor: {
                                                        xtype: 'textfield',
                                                        id: 'netWt',
                                                        itemId: 'netWt',
                                                        name: 'netWt',
                                                        allowBlank: false,
                                                        validateBlank: true
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    dataIndex: 'weightUnit',
                                                    text: 'Weight Unit',
                                                    editor: {
                                                        xtype: 'combobox',
                                                        id: 'wtUnit',
                                                        itemId: 'wtUnit',
                                                        name: 'wtUnit',
                                                        allowBlank: false,
                                                        validateBlank: true,
                                                        store: [
                                                            'kg',
                                                            'ton',
                                                            'lbs'
                                                        ],
                                                        listeners: {
                                                            change: 'onWtUnitChange'
                                                        }
                                                    }
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting'
                                                }
                                            ],
                                            selModel: {
                                                selType: 'checkboxmodel'
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'checkboxgroup',
                                                    flex: 1,
                                                    width: 400,
                                                    items: [
                                                        {
                                                            xtype: 'checkboxfield',
                                                            name: 'validWt',
                                                            boxLabel: 'Valid Weight',
                                                            inputValue: '1',
                                                            uncheckedValue: '0'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            name: 'approveDoc',
                                                            boxLabel: 'Valid Documents',
                                                            inputValue: '1',
                                                            uncheckedValue: '0'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            name: 'goodCustomer',
                                                            boxLabel: 'Good Customer',
                                                            inputValue: '1',
                                                            uncheckedValue: '0'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    id: 'createResetBtn',
                                    itemId: 'createResetBtn',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'button',
                                    id: 'validateResetBtn',
                                    itemId: 'validateResetBtn',
                                    text: 'Validate'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onContainerAfterRender: function(component, eOpts) {
        Ext.define('MyMap', {
            extend: 'Ext.ux.Carousel',
            alias: 'widget.mycarousel',
                        autoShow: true,
                        layout: 'fit',
                        title: 'GMap Window',
                        closeAction: 'hide',
                        width:450,
                        height:450,
                        border: false,
                        x: 40,
                        y: 60,
                        items: {
                            xtype: 'gmappanel',
                            center: {
                                geoCodeAddr: '4 Yawkey Way, Boston, MA, 02215-3409, USA',
                                marker: {title: 'Fenway Park'}
                            },
                            markers: [{
                                lat: 42.339641,
                                lng: -71.094224,
                                title: 'Boston Museum of Fine Arts',
                                listeners: {
                                    click: function(e){
                                        Ext.Msg.alert('It\'s fine', 'and it\'s art.');
                                    }
                                }
                            },{
                                lat: 42.339419,
                                lng: -71.09077,
                                title: 'Northeastern University'
                            }]
                        }
                    });
    },

    onFromdateBlur: function(component, event, eOpts) {
        if (Ext.getCmp('fromDate').getValue() > Ext.getCmp('toDate').getValue()){
            alert('From date should be later than To Date');
            conponent.setValue('');
            Ext.getCmp('toDate').setValue('');
        }
    },

    onToDateBlur: function(component, event, eOpts) {
        if (Ext.getCmp('toDate').getValue() < Ext.getCmp('fromDate').getValue()){
            alert('From date should be later than To Date');
            conponent.setValue('');
            Ext.getCmp('fromDate').setValue('');
        }
    },

    onBookingFromCityBlur: function(component, event, eOpts) {
        var from = Ext.getCmp('bookingFromCity').getValue(),
            to = Ext.getCmp('bookingToCity').getValue();

        if (from == to){
            alert('From City should not be the same as To City! Please change');
        Ext.getCmp('bookingFromCity').setValue('');
        Ext.getCmp('bookingToCity').setValue('');
        }


    },

    onBookingToCityBlur: function(component, event, eOpts) {
        var from = Ext.getCmp('bookingFromCity').getValue(),
            to = Ext.getCmp('bookingToCity').getValue();

        if (from == to){
            alert('From City should not be the same as To City! Please change');
        Ext.getCmp('bookingFromCity').setValue('');
        Ext.getCmp('bookingToCity').setValue('');

        }

    },

    onWtUnitChange: function(field, newValue, oldValue, eOpts) {

        var    gross = Ext.getCmp('netWt').getValue(),
            net = Ext.getCmp('grossWt').getValue();

        console.log(oldValue);
        console.log(newValue);
        if(oldValue == 'kg'){
            if(newValue == 'lbs'){
                 Ext.getCmp('netWt').setValue(net*2.20462);
                 Ext.getCmp('grossWt').setValue(gross*2.20462);
            } else if (newValue == 'ton'){

                 Ext.getCmp('netWt').setValue(net/907.185);
                 Ext.getCmp('grossWt').setValue(gross/907.185);

            }

        } else if(oldValue == 'lbs'){
            if(newValue == 'kg'){

                 Ext.getCmp('netWt').setValue(net/0.453592);
                 Ext.getCmp('grossWt').setValue(gross/0.453592);

            } else if (newValue == 'ton'){

                Ext.getCmp('netWt').setValue(net/0.000453592);
                 Ext.getCmp('grossWt').setValue(gross/0.000453592);
            }

        } else if(oldValue == 'ton'){
            if(newValue == 'lbs'){

                Ext.getCmp('netWt').setValue(net*2204.62);
                 Ext.getCmp('grossWt').setValue(gross*2204.62);

            } else if (newValue == 'kg'){
                Ext.getCmp('netWt').setValue(net*1000);
                 Ext.getCmp('grossWt').setValue(gross*1000);

            }

        }

        console.log(net);




    }

});