/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.MyPanel',

    alternateClassName: [
        'myPanel'
    ],
    requires: [
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label'
    ],

    id: 'MyPanel',
    itemId: 'MyPanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 500,
            id: 'carr',
            itemId: 'carr',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            listeners: {
                afterrender: 'onContainerAfterRender'
            }
        },
        {
            xtype: 'container',
            padding: 10,
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/bg/map.PNG)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            flex: 1,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img5',
                                    itemId: 'img5',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cservices.png',
                                    listeners: {
                                        afterrender: 'onImageAfterRender'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img6',
                                    itemId: 'img6',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cschedules.png',
                                    listeners: {
                                        afterrender: 'onImg6AfterRender'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img7',
                                    itemId: 'img7',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cvgminfo.png',
                                    listeners: {
                                        afterrender: 'onImg7AfterRender'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img8',
                                    itemId: 'img8',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cterminalinfo.png',
                                    listeners: {
                                        afterrender: 'onImg8AfterRender'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img9',
                                    itemId: 'img9',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cvesselinfo.png',
                                    listeners: {
                                        afterrender: 'onImg9AfterRender'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img10',
                                    itemId: 'img10',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cvesseltracking.png',
                                    listeners: {
                                        afterrender: 'onImg10AfterRender'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img11',
                                    itemId: 'img11',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Ccontainerinfo.png',
                                    listeners: {
                                        afterrender: 'onImg11AfterRender'
                                    }
                                },
                                {
                                    xtype: 'image',
                                    height: 132,
                                    id: 'img12',
                                    itemId: 'img12',
                                    padding: 10,
                                    width: 132,
                                    src: '%5Cimages%5Csettings%5Cratestariff.png',
                                    listeners: {
                                        afterrender: 'onImg12AfterRender'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            html: '<h2 style="font-size: 70px;color: #11428f;line-height: 1.2;text-align: left;font-family:Roboto;font-weight:100;font-style:normal" class="vc_custom_heading">quick<br /> access</h2><p><span style="color: #11428f;">Direct to the major features facilitating your shipments.</span></p>'
                        }
                    ]
                }
            ]
        }
    ],

    onContainerAfterRender: function(component, eOpts) {
        var store = Ext.create('Ext.data.Store', {
            fields: ['title', 'imgSrc'],
            data: [
                   {
                       title: 'Cloud Forest',
                       imgSrc: '/images/bg/header.png'},
                   {
                       title: 'Cloud Forest 2',
                       imgSrc: '/images/bg/terminalDefault.jpg'},
                   {
                       title: 'Cloud Forest',
                       imgSrc: '/images/bg/cargoDefault.jpg'}]
        });

        //Define a customized carousel
        Ext.define('MyCarousel', {
            extend: 'Ext.ux.Carousel',
            alias: 'widget.mycarousel',
            template: '<img src="{imgSrc}" alt="{title}" style="width:1500px;height:500px" />',
            store: store,
            interval: 3000,
            direction: 'left',
            loop: true,
            buttons: false,
            puaseOnHover: true,
            width: 2000,
            height: 500,
            flex: 1

        });

        var view = Ext.create('widget.mycarousel');


        component.add(view);




    },

    onImageAfterRender: function(component, eOpts) {


        component.el.on('mouseout', function() {Ext.getCmp('img5').setSrc('/images/settings/services.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img5').setSrc('/images/readMore.png');});
    },

    onImg6AfterRender: function(component, eOpts) {


        component.el.on('mouseout', function() {Ext.getCmp('img6').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img6').setSrc('/images/readMore.png');});
    },

    onImg7AfterRender: function(component, eOpts) {


        component.el.on('mouseout', function() {Ext.getCmp('img7').setSrc('/images/settings/vgminfo.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img7').setSrc('/images/readMore.png');});
    },

    onImg8AfterRender: function(component, eOpts) {


        component.el.on('mouseout', function() {Ext.getCmp('img8').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img8').setSrc('/images/readMore.png');});
    },

    onImg9AfterRender: function(component, eOpts) {
        component.el.on('mouseout', function() {Ext.getCmp('img9').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img9').setSrc('/images/readMore.png');});
    },

    onImg10AfterRender: function(component, eOpts) {
        component.el.on('mouseout', function() {Ext.getCmp('img10').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img10').setSrc('/images/readMore.png');});
    },

    onImg11AfterRender: function(component, eOpts) {
        component.el.on('mouseout', function() {Ext.getCmp('img11').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img11').setSrc('/images/readMore.png');});
    },

    onImg12AfterRender: function(component, eOpts) {
        component.el.on('mouseout', function() {Ext.getCmp('img12').setSrc('/images/settings/schedules.png');});
        component.el.on('mouseover', function() {Ext.getCmp('img12').setSrc('/images/readMore.png');});
    }

});