/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.Img'
    ],

    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    x: 0,
                    y: 0,
                    height: 353,
                    layout: 'absolute',
                    title: 'Img Panel',
                    items: [
                        {
                            xtype: 'image',
                            x: 800,
                            y: 30,
                            height: 275,
                            width: 650,
                            focusOnToFront: false,
                            toFrontOnShow: false,
                            src: 'img/gray.png'
                        },
                        {
                            xtype: 'container',
                            height: 330,
                            width: 750,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'image',
                                    x: 40,
                                    y: 30,
                                    height: 275,
                                    width: 650,
                                    focusOnToFront: false,
                                    toFrontOnShow: false,
                                    src: 'img/gray.png'
                                },
                                {
                                    xtype: 'image',
                                    x: 50,
                                    y: 40,
                                    draggable: true,
                                    height: 100,
                                    id: 'img1',
                                    width: 100,
                                    src: 'img/wew.png'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    x: 0,
                    y: 390,
                    height: 365,
                    layout: 'absolute',
                    title: 'Drop Panel'
                }
            ]
        });

        me.callParent(arguments);
    }

});