/*
 * File: app/view/adminToolbar.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.adminToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.adminToolbar',

    requires: [
        'Ext.Img',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    height: 69,
    id: 'adminToolbar',
    itemId: 'adminToolbar',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'image',
            height: 59,
            width: 95,
            src: '/images/Kerberos.png'
        },
        {
            xtype: 'button',
            id: 'menuBtn1',
            itemId: 'menuBtn',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/menu.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onMenuBtnClick1'
            }
        },
        {
            xtype: 'tbfill'
        },
        {
            xtype: 'button',
            text: 'MyButton',
            menu: {
                xtype: 'menu',
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Account'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Logout'
                    }
                ]
            }
        }
    ],

    onMenuBtnClick1: function(button, e, eOpts) {

        if(Ext.getCmp('home').text == 'Home'){

        Ext.getCmp('home').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/home.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('home').setText('');

        Ext.getCmp('kerberos').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/building.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('kerberos').setText('');

        Ext.getCmp('create').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/create.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('create').setText('');

        Ext.getCmp('search').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/search.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('search').setText('');

        Ext.getCmp('users').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/users.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('users').setText('');

        Ext.getCmp('about').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(images/tools/about.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
        });
        Ext.getCmp('about').setText('');


        } else{
            Ext.getCmp('home').setStyle({background:'#ffffff'});
            Ext.getCmp('home').setText('Home');
            Ext.getCmp('kerberos').setStyle({background:'#ffffff'});
            Ext.getCmp('kerberos').setText('Kerberos Booking');
            Ext.getCmp('create').setStyle({background:'#ffffff'});
            Ext.getCmp('create').setText('Create Booking');
             Ext.getCmp('search').setStyle({background:'#ffffff'});
            Ext.getCmp('search').setText('Search Booking');
             Ext.getCmp('users').setStyle({background:'#ffffff'});
            Ext.getCmp('users').setText('User Management');
            Ext.getCmp('about').setStyle({background:'#ffffff'});
            Ext.getCmp('about').setText('About');


        }





    }

});