/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.LoginForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginform',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    modal: true,
    flex: 1,
    height: 247,
    shrinkWrap: 3,
    width: 372,
    manageHeight: false,
    title: 'Login',

    items: [
        {
            xtype: 'form',
            bodyPadding: 20,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'usernameTxt',
                            itemId: 'usernameTxt',
                            margin: '0 0 20 0',
                            fieldLabel: 'Username',
                            msgTarget: 'title',
                            name: 'identity',
                            allowBlank: false,
                            blankText: 'Enter your Username.',
                            regexText: 'Enter your username.'
                        },
                        {
                            xtype: 'textfield',
                            id: 'passwordTxt',
                            itemId: 'passwordTxt',
                            margin: '0 0 10 0',
                            fieldLabel: 'Password',
                            msgTarget: 'title',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'Enter your password.'
                        },
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            boxLabel: 'Remember me?'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    formBind: true,
                                    id: 'registerBtn',
                                    itemId: 'registerBtn',
                                    margin: '0 15 0 0',
                                    scale: 'medium',
                                    text: 'Register'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    formBind: true,
                                    id: 'logBtn',
                                    itemId: 'logBtn',
                                    margin: '0 15 0 0',
                                    scale: 'medium',
                                    text: 'Login'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});