/*
 * File: app/view/toolbarIcn.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.toolbarIcn', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.toolbarIcn',

    requires: [
        'KerberosBooking.view.toolbarIcnViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    viewModel: {
        type: 'toolbaricn'
    },
    id: 'toolbarIcn',
    itemId: 'toolbarIcn',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'button',
            flex: 1,
            height: 59,
            id: 'home1',
            itemId: 'home',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/home.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            width: 78
        },
        {
            xtype: 'button',
            flex: 1,
            id: 'kerberos1',
            itemId: 'kerberos',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/building.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onKerberosClick1'
            }
        },
        {
            xtype: 'button',
            flex: 1,
            id: 'create1',
            itemId: 'create',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/create.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onCreateClick1'
            }
        },
        {
            xtype: 'button',
            flex: 1,
            id: 'search1',
            itemId: 'search',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/search.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onSearchClick1'
            }
        },
        {
            xtype: 'button',
            flex: 1,
            id: 'users1',
            itemId: 'users',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/users.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onUsersClick1'
            }
        },
        {
            xtype: 'button',
            flex: 1,
            id: 'about1',
            itemId: 'about',
            style: {
                background: '#ffffff',
                backgroundImage: 'url(images/tools/about.png)',
                backgroundSize: '100% 100%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'bottom left',
                
            },
            listeners: {
                click: 'onAboutClick1'
            }
        },
        {
            xtype: 'tbspacer',
            flex: 1
        }
    ],

    onKerberosClick1: function(button, e, eOpts) {

    },

    onCreateClick1: function(button, e, eOpts) {

    },

    onSearchClick1: function(button, e, eOpts) {

    },

    onUsersClick1: function(button, e, eOpts) {

    },

    onAboutClick1: function(button, e, eOpts) {

    }

});