/*
 * File: app/view/viewUsersPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.viewUsersPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.viewUsersPanel',

    alternateClassName: [
        'viewUsersPanel'
    ],
    requires: [
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Boolean',
        'Ext.form.field.Checkbox'
    ],

    id: 'viewUsersPanel',
    itemId: 'viewUsersPanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 500,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    flex: 1,
                    width: 201,
                    src: '%5Cimages%5Cbg%5Ccustomer.jpg'
                }
            ]
        },
        {
            xtype: 'container',
            height: 200,
            html: '<iframe\n  width="600"\n  height="450"\n  frameborder="0" style="border:0"\n  src="https://www.google.com.sg/maps/@1.3437459,103.8240449,11z?hl=en" allowfullscreen>\n</iframe>',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    id: 'searchUsersPanel',
                    itemId: 'searchUsersPanel',
                    bodyPadding: 10,
                    title: 'User Management',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    width: 343,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'viewBkgPanel1',
                                            itemId: 'viewBkgPanel',
                                            fieldLabel: 'Username',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'First Name',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Last Name',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'toolbar',
                                            padding: '',
                                            layout: {
                                                type: 'hbox',
                                                padding: 5
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbfill',
                                                    flex: 1,
                                                    width: 235
                                                },
                                                {
                                                    xtype: 'button',
                                                    dock: 'right',
                                                    style: {
                                                        background: '#FFFFFF'
                                                    },
                                                    scale: 'medium',
                                                    text: 'Submit'
                                                },
                                                {
                                                    xtype: 'button',
                                                    scale: 'medium',
                                                    text: 'Reset'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    height: 300,
                    padding: 10,
                    resizable: true,
                    bodyPadding: '',
                    title: '',
                    store: 'userManagement',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'username',
                            text: 'Username'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'firstname',
                            text: 'First Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'lastname',
                            text: 'Last Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'role',
                            text: 'Role'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'email',
                            text: 'Email'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'contactnumber',
                            text: 'Contact Number'
                        },
                        {
                            xtype: 'booleancolumn',
                            flex: 1,
                            text: 'canViewBooking',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            flex: 1,
                            text: 'canCreateBooking',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            text: 'canManageUsers',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'addUser',
                                    itemId: 'addUser',
                                    style: {
                                        background: '#FFFFFF'
                                    },
                                    text: 'Add',
                                    listeners: {
                                        click: 'onAddUserClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    style: {
                                        background: '#FFFFFF'
                                    },
                                    text: 'Edit'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Delete'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onAddUserClick: function(button, e, eOpts) {
        Ext.create('KerberosBooking.view.RegisterForm').show();
    }

});