/*
 * File: app/view/Gallery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Gallery', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.Img',
        'Ext.button.Button'
    ],

    id: 'gridView1',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Gallery',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'img/pangasinan.jpg'
                        },
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'img/slinky.jpg'
                        },
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'img/payslip.jpg'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    width: 100,
                    text: 'Return',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.Home',{title:'Home'}));
    }

});