/*
 * File: app/view/Home.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Home', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.TextArea'
    ],

    id: 'homeView',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Menu',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Home'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        itemId: 'chartItem',
                                        href: '',
                                        text: 'Chart',
                                        listeners: {
                                            click: {
                                                fn: me.onChartItemClick,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Gallery',
                                        listeners: {
                                            click: {
                                                fn: me.onMenuitemClick1,
                                                scope: me
                                            }
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Grid',
                                        listeners: {
                                            click: {
                                                fn: me.onMenuitemClick,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 160,
                    bodyPadding: 10,
                    title: 'Welcome!',
                    items: [
                        {
                            xtype: 'label',
                            id: 'label1',
                            text: 'Type something in the text area to display here.'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            id: 'textArea1',
                            fieldLabel: 'Input'
                        },
                        {
                            xtype: 'button',
                            id: 'displayButton',
                            text: 'Display',
                            tooltip: 'Click button to display text into label',
                            listeners: {
                                click: {
                                    fn: me.onDisplayButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onChartItemClick: function(item, e, eOpts) {
        alert('w0w');
    },

    onMenuitemClick1: function(item, e, eOpts) {
        this.push(Ext.create('MyApp.view.Gallery',{title:'Gallery'}));
    },

    onMenuitemClick: function(item, e, eOpts) {
        this.push(Ext.create('MyApp.view.Grid',{title:'Grid'}));
    },

    onDisplayButtonClick: function(button, e, eOpts) {
        Ext.Msg.confirm("Confirmation", "Display Text?", function(btnText){
                        if(btnText === "no"){
                            Ext.Msg.alert("Alert", "You have confirmed 'No'.");
                        }
                        else if(btnText === "yes"){
                            var textArea = Ext.getCmp('textArea1').getValue();
                            Ext.getCmp('label1').setText(textArea);
                            Ext.getCmp('textArea1').setValue('');
                        }
                    }, this);
    }

});