/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.MyModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.MyModel',
            storeId: 'MyStore',
            data: [
                {
                    value: 787,
                    name: 'Artemisia'
                },
                {
                    value: 912,
                    name: 'Elonia'
                },
                {
                    value: 924,
                    name: 'Sea of Desert'
                },
                {
                    value: 64,
                    name: 'Abysmal Cronium'
                },
                {
                    value: 870,
                    name: 'Crystal Kingdom'
                },
                {
                    value: 391,
                    name: 'Illumin'
                },
                {
                    value: 999,
                    name: 'Netherworld'
                },
                {
                    value: 292,
                    name: 'Others'
                }
            ]
        }, cfg)]);
    }
});