/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.panel.Panel',
        'Ext.Img'
    ],

    viewModel: {
        type: 'myviewport'
    },
    defaultListenerScope: true,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    height: 381,
                    layout: 'absolute',
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'image',
                            draggable: true,
                            height: 201,
                            width: 201,
                            src: '%5Capp%5Cimages%5CbritishCat.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 320,
                            y: 170,
                            draggable: true,
                            height: 201,
                            width: 201,
                            src: '%5Capp%5Cimages%5ChuskyDog.jpg'
                        },
                        {
                            xtype: 'image',
                            x: 40,
                            y: 400,
                            draggable: true,
                            height: 201,
                            width: 201,
                            src: '%5Capp%5Cimages%5ClonghairCat.jpg'
                        }
                    ]
                }
            ],
            listeners: {
                render: 'onContainerRender'
            }
        }
    ],

    onContainerRender: function(component, eOpts) {
        component.dragZone = Ext.create('Ext.dd.DragZone', component.getEl(), {
            getDragData: function(e) {
                var sourceEl = e.getTarget(component.itemSelector, 10), d;
                if (sourceEl) {
                    d = sourceEl.cloneNode(true);
                    d.id = Ext.id();
                    return (component.dragData = {
                        sourceEl: sourceEl,
                        repairXY: Ext.fly(sourceEl).getXY(),
                        ddel: d,
                        patientData: component.getRecord(sourceEl).data
                    });
                }
            },
            getRepairXY: function() {
                return this.dragData.repairXY;
            }
        });

        console.log(component.dragZone);
    }

});