/*
 * File: app/controller/Exer4.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sample.controller.Exer4', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'cbPortId',
            selector: '#cbPortId'
        },
        {
            ref: 'txtFilter',
            selector: '#txtFilter'
        },
        {
            ref: 'btnSearch',
            selector: '#btnSearch'
        },
        {
            ref: 'btnReset',
            selector: '#btnReset'
        },
        {
            ref: 'cbType',
            selector: '#cbType'
        }
    ],

    onCbPortIdChange: function(field, newValue, oldValue, eOpts) {

    },

    onCbTypeChange: function(field, newValue, oldValue, eOpts) {

    },

    init: function(application) {
        this.control({
            "#cbPortId": {
                change: this.onCbPortIdChange
            },
            "#cbType": {
                change: this.onCbTypeChange
            }
        });
    }

});
