/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Sample.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.container.Container',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 193,
    itemId: 'winForm',
    width: 698,
    title: 'Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 58,
                    items: [
                        me.processCbPortId({
                            xtype: 'combobox',
                            itemId: 'cbPortId',
                            width: 674,
                            fieldLabel: 'Name',
                            forceSelection: true
                        })
                    ]
                },
                {
                    xtype: 'container',
                    height: 35,
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.Msg.alert("Hello","Name");
                            },
                            itemId: 'btnSearch',
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnReset',
                            text: 'Reset'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 31,
                    items: [
                        {
                            xtype: 'combobox',
                            itemId: 'cbType',
                            width: 339,
                            fieldLabel: 'Type:'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processCbPortId: function(config) {
        //this.getCbPortId.setValue('111');

        return config;

        //var cust_type_store = new Ext.data.SimpleStore({
        //fields: ['id', 'cust_type'],
        //data: [['1', 'Customer'], ['2', 'Friend'], ['3', 'Family']]
        //});
        //Ext.getCmp('combo').setValue('2');

        //var combo = Ext.create('Ext.form.field.ComboBox', {
            //store: ['Red', 'Green', 'Blue']
        //});

        Ext.create('Ext.form.field.CbPortId', {
            displayField: 'utensil',
            queryMode: 'local',

            store: {
                fields: ['utensil'],

                data: [
                    {utensil: 'Knife'},
                    {utensil: 'Fork'},
                    {utensil: 'Spoon'}
                ]
            }
        });

    }

});