/*
 * File: app/view/adminPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.adminPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.adminPanel',

    alternateClassName: [
        'adminPanel'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.Img',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.toolbar.Spacer'
    ],

    flex: 1,
    id: 'adminPanel',
    itemId: 'adminPanel',
    scrollable: true,
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            region: 'center',
            flex: 1,
            layout: 'card'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 69,
            items: [
                {
                    xtype: 'image',
                    height: 59,
                    width: 95,
                    src: 'resources/img/kerberos.png'
                },
                {
                    xtype: 'button',
                    id: 'menuBtn',
                    itemId: 'menuBtn',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/menu.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    },
                    listeners: {
                        click: 'onMenuBtnClick'
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Admin',
                    id : 'adminViewBtn',
                    itemId: 'adminViewBtn',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Account'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Logout',
                                id: 'adminLogout',
                                itemId: 'adminLogout'
                            }
                        ]
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'left',
            id: 'toolbarIcon',
            itemId: 'toolbarIcon',
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    height: 59,
                    id: 'home',
                    itemId: 'home',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/home.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    },
                    width: 78
                },
                {
                    xtype: 'button',
                    flex: 1,
                    id: 'kerberos',
                    itemId: 'kerberos',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/building.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    id: 'create',
                    itemId: 'create',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/create.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    id: 'search',
                    itemId: 'search',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/search.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    id: 'users',
                    itemId: 'users',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/users.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    id: 'about',
                    itemId: 'about',
                    style: {
                        background: '#ffffff',
                        backgroundImage: 'url(resources/img/about.png)',
                        backgroundSize: '50% 50%',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        
                    }
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'left',
            hidden: true,
            id: 'toolbarWords',
            itemId: 'toolbarWords',
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Home'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Keberos'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Create Booking'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Search Booking'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Manage Users'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'About'
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                }
            ]
        }
    ],

    onMenuBtnClick: function(button, e, eOpts) {

        if(Ext.getCmp('home').text == 'Home'){

        Ext.getCmp('home').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/home.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('home').setText('');

        Ext.getCmp('kerberos').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/building.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('kerberos').setText('');

        Ext.getCmp('create').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/create.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('create').setText('');

        Ext.getCmp('search').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/search.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('search').setText('');

        Ext.getCmp('users').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/users.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('users').setText('');

        Ext.getCmp('about').setStyle({
                background:'#ffffff',
                backgroundImage: 'url(resources/img/about.png)',
                backgroundSize: '50% 50%',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center',
        });
        Ext.getCmp('about').setText('');


        } else{
            Ext.getCmp('home').setStyle({background:'#ffffff'});
            Ext.getCmp('home').setText('Home');
            Ext.getCmp('kerberos').setStyle({background:'#ffffff'});
            Ext.getCmp('kerberos').setText('Kerberos Booking');
            Ext.getCmp('create').setStyle({background:'#ffffff'});
            Ext.getCmp('create').setText('Create Booking');
             Ext.getCmp('search').setStyle({background:'#ffffff'});
            Ext.getCmp('search').setText('Search Booking');
             Ext.getCmp('users').setStyle({background:'#ffffff'});
            Ext.getCmp('users').setText('User Management');
            Ext.getCmp('about').setStyle({background:'#ffffff'});
            Ext.getCmp('about').setText('About');


        }





    }

});