/*
 * File: app/view/createBkgPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.createBkgPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.createBkgPanel',

    alternateClassName: [
        'createBkgPanel'
    ],
    requires: [
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Fill'
    ],

    id: 'createBkgPanel',
    itemId: 'createBkgPanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 900,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    dock: 'top',
                    flex: 1,
                    height: 201,
                    hidden: true,
                    width: 201,
                    src: 'resources/img/englishmap.png'
                }
            ],
            listeners: {
                afterrender: 'onContainerAfterRender'
            }
        },
        {
            xtype: 'container',
            scrollable: true,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    id: 'createBookingPanel',
                    itemId: 'createBookingPanel',
                    layout: 'auto',
                    bodyPadding: 10,
                    title: 'Create Booking',
                    titleAlign: 'left',
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            id: 'bookingPanel',
                            itemId: 'bookingPanel',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    disabled: true,
                                    padding: 10,
                                    fieldLabel: 'Booking Number'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    padding: 10,
                                    fieldLabel: 'Booking Office'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    padding: 10,
                                    text: 'Booking Status'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            id: 'bookingInfoPanel',
                            itemId: 'bookingInfoPanel',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            padding: 10,
                                            fieldLabel: 'Shipper',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            padding: 10,
                                            fieldLabel: 'From City',
                                            labelWidth: 120
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            padding: 10,
                                            fieldLabel: 'Consignee',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            padding: 10,
                                            fieldLabel: 'To City',
                                            labelWidth: 120
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'containerPanel',
                            itemId: 'containerPanel',
                            padding: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    padding: 10,
                                                    fieldLabel: 'From City',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    padding: 10,
                                                    fieldLabel: 'Cargo Nature',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    padding: 10,
                                                    fieldLabel: 'Cargo Description',
                                                    labelWidth: 120
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            padding: '',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    padding: 10,
                                                    fieldLabel: 'To City',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    padding: 10,
                                                    fieldLabel: 'Quantity',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    padding: 10,
                                                    fieldLabel: 'HS Code',
                                                    labelWidth: 120
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: '',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    dataIndex: 'string',
                                                    text: 'Reference Number'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    text: 'Container Number'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    text: 'Gross Weight',
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    text: 'Net Weight',
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    text: 'Weight Unit',
                                                    editor: {
                                                        xtype: 'combobox'
                                                    }
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            text: 'Add'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Delete'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Copy'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'checkboxgroup',
                                                    flex: 1,
                                                    width: 400,
                                                    items: [
                                                        {
                                                            xtype: 'checkboxfield',
                                                            boxLabel: 'Valid Weight'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            boxLabel: 'Valid Documents'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            boxLabel: 'Good Customer'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            text: 'Validate'
                        }
                    ]
                }
            ]
        }
    ],

    onContainerAfterRender: function(component, eOpts) {
        Ext.define('MyMap', {
            extend: 'Ext.ux.Carousel',
            alias: 'widget.mycarousel',
                        autoShow: true,
                        layout: 'fit',
                        title: 'GMap Window',
                        closeAction: 'hide',
                        width:450,
                        height:450,
                        border: false,
                        x: 40,
                        y: 60,
                        items: {
                            xtype: 'gmappanel',
                            center: {
                                geoCodeAddr: '4 Yawkey Way, Boston, MA, 02215-3409, USA',
                                marker: {title: 'Fenway Park'}
                            },
                            markers: [{
                                lat: 42.339641,
                                lng: -71.094224,
                                title: 'Boston Museum of Fine Arts',
                                listeners: {
                                    click: function(e){
                                        Ext.Msg.alert('It\'s fine', 'and it\'s art.');
                                    }
                                }
                            },{
                                lat: 42.339419,
                                lng: -71.09077,
                                title: 'Northeastern University'
                            }]
                        }
                    });
    }

});