/*
 * File: app/view/mainViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.mainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainViewport',

    alternateClassName: [
        'mainViewport'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.Img',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    id: 'mainViewport',
    itemId: 'mainViewport',
    scrollable: true,
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'toolbar',
            margins: '0 0 0 0',
            region: 'north',
            dock: 'top',
            height: 63,
            margin: '0 0 0 0',
            padding: 0,
            items: [
                {
                    xtype: 'button',
                    id: 'homeBtn',
                    itemId: 'homeBtn',
                    scale: 'medium',
                    text: 'Home'
                },
                {
                    xtype: 'button',
                    margins: '',
                    id: 'kerberosBtn',
                    itemId: 'kerberosBtn',
                    margin: '0 0 0 0',
                    scale: 'medium',
                    text: 'Kerberos Shipping'
                },
                {
                    xtype: 'button',
                    id: 'createBtn',
                    itemId: 'createBtn',
                    scale: 'medium',
                    text: 'Create Booking'
                },
                {
                    xtype: 'button',
                    id: 'viewBtn',
                    itemId: 'viewBtn',
                    scale: 'medium',
                    text: 'View Booking'
                },
                {
                    xtype: 'button',
                    id: 'aboutBtn',
                    itemId: 'aboutBtn',
                    scale: 'medium',
                    text: 'About'
                },
                {
                    xtype: 'button',
                    margins: '0 0 0 0',
                    dock: 'bottom',
                    id: 'loginBtn',
                    itemId: 'loginBtn',
                    margin: '0 0 0 0',
                    scale: 'medium',
                    text: 'Login'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'image',
                    flex: 1,
                    flex: 1,
                    height: 31,
                    width: 156,
                    src: 'resources/img/KerberosBanner.png'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            region: 'center',
            layout: 'card'
        }
    ],
    listeners: {
        afterrender: 'onMainViewportAfterRender'
    },

    onMainViewportAfterRender: function(component, eOpts) {
        var viewport = Ext.ComponentQuery.query('mainViewport')[0];
        var center = viewport.down('[region=center]');
        var mainPanel = Ext.ComponentQuery.query('MyPanel')[0];

        var view = Ext.create('MyPanel');
        Ext.getCmp('createBtn').hide();
        Ext.getCmp('viewBtn').hide();
        //viewBtn
        center.add(view);

    }

});