/*
 * File: app/view/myHomePanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.myHomePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.myHomePanel',

    alternateClassName: [
        'myHomePanel'
    ],
    requires: [
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label'
    ],

    id: 'myHomePanel',
    itemId: 'myHomePanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 308,
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    dock: 'top',
                    flex: 1,
                    src: 'resources/img/aboutus-vision.jpg'
                }
            ]
        },
        {
            xtype: 'container',
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            html: '<h1>COMMITMENT AND EXPERIENCE</h1> </br><h4>The company is commercially headquartered in Dubai and Hong Kong, two of the busiest container ports in the world.  Our strength is our strategic positioning in the dynamic markets of the Middle East, China, South East Asia, India and Africa. Our network and understanding of these key trading and commercial centers means that we can provide world class services to our customers.</h4>'
                        }
                    ]
                },
                {
                    xtype: 'image',
                    height: 300,
                    id: 'img3',
                    itemId: 'img3',
                    width: 300,
                    src: 'resources/img/portHome.png'
                    
                }
            ]
        },
        {
            xtype: 'container',
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 300,
                    width: 300,
                    src: 'resources/img/shipHome.png'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            padding: 10,
                            html: '<h1>OUR TEAM</h1> </br><h4>Emirates Shipping Line has an extensive team of multinational and experienced shipping professionals in place, who are committed to individual customer solutions and ensuring quality in whatever we do.</h4>'
                        }
                    ]
                }
            ]
        }
    ]

});