/*
 * File: app/view/myHomePanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.myHomePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.myHomePanel',

    alternateClassName: [
        'myHomePanel'
    ],
    requires: [
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label'
    ],

    id: 'myHomePanel',
    itemId: 'myHomePanel',
    scrollable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 308,
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    flex: 1,
                    dock: 'top',
                    flex: 1,
                    src: '/images/bg/aboutus-vision.jpg'
                }
            ]
        },
        {
            xtype: 'container',
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'image',
                    height: 134,
                    id: 'img3',
                    itemId: 'img3',
                    width: 169,
                    src: '/images/portHome.jpg',
                    listeners: {
                        afterrender: 'onImageAfterRender'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            padding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 131,
                    width: 173,
                    src: '/images/shipHome.jpeg'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            text: 'My Label'
                        }
                    ]
                }
            ]
        }
    ],

    onImageAfterRender: function(component, eOpts) {


        component.el.on('mouseout', function() {Ext.getCmp('img3').setSrc('/images/portHome.jpg');});
        component.el.on('mouseover', function() {Ext.getCmp('img3').setSrc('/images/KerberosBanner.jpg');});
    }

});