/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.MyPanel',

    alternateClassName: [
        'MyPanel'
    ],
    requires: [
        'Ext.container.Container',
        'Ext.Img',
        'Ext.form.Label'
    ],

    id: 'MyPanel',
    itemId: 'MyPanel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 138,
                    width: 170,
                    src: '/images/ship1.jpg'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            text: 'My Label'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1
                },
                {
                    xtype: 'image',
                    height: 134,
                    width: 169,
                    src: '/images/ship1.jpg'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 131,
                    width: 173,
                    src: '/images/ship3.jpg'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'label',
                            text: 'My Label'
                        }
                    ]
                }
            ]
        }
    ]

});