/*
 * File: app/view/RegisterForm.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.RegisterForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.registerform',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    modal: true,
    height: 450,
    itemId: 'registerForm',
    id: 'registerForm',
    width: 400,
    title: 'Register',

    items: [
        {
            xtype: 'form',
            itemId: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'First Name',
                    labelAlign: 'right',
                    id: 'firstName',
                    msgTarget: 'title',
                    name: 'firstName',
                    allowBlank: false,
                    blankText: 'Enter your first name.'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'Last Name',
                    id: 'lastName',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'lastName',
                    allowBlank: false,
                    blankText: 'Enter your last name.'
                }
                ,
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'Email',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    id : 'email',
                    name: 'email',
                    allowBlank: false,
                    blankText: 'Enter your email.'
                }, {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'Contact Number',
                    labelAlign: 'right',
                    id: 'contactNo',
                    msgTarget: 'title',
                    name: 'contactNo',
                    allowBlank: false,
                    blankText: 'Enter your contact number.'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'Username',
                    id: 'username',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'username',
                    allowBlank: false,
                    blankText: 'Choose a username.'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    margin: '0 0 10 0',
                    fieldLabel: 'Password',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'password',
                    id: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    blankText: 'Choose a password.'
                },  {
                    xtype: 'radiogroup',
                    id: 'roleUser',
                    itemId: 'roleUser',
                    width: 400,
                    fieldLabel: 'Role',
                    items: [
                        {
                            xtype: 'radiofield',
                            id: 'radioCustomerUser',
                            itemId: 'radioCustomerUser',
                            name: 'role',
                            boxLabel: 'Customer',
                            inputValue: 'Customer'
                        },
                        {
                            xtype: 'radiofield',
                            id: 'radioCSVUser',
                            itemId: 'radioCSVUser',
                            name: 'role',
                            boxLabel: 'CSV',
                            inputValue: 'CSV'
                        },
                        {
                            xtype: 'radiofield',
                            id: 'radioAdminUser',
                            itemId: 'radioAdminUser',
                            name: 'role',
                            boxLabel: 'Admin',
                            inputValue: 'Admin'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    formBind: true,
                    id: 'registerButton',
                    itemId: 'registerButton',
                    scale: 'medium',
                    text: 'Register'
                    
                }
            ]
        }
    ]

});