/*
 * File: app/view/viewBookingPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KerberosBooking.view.viewBookingPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.viewBookingPanel',

    alternateClassName: [
        'viewBookingPanel'
    ],
    requires: [
    	'KerberosBooking.model.AllBookingsModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel'
    ],

    id: 'viewBookingPanel',
    itemId: 'viewBookingPanel',
    scrollable: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            flex: 1,
            html: '<iframe\n  width="600"\n  height="450"\n  frameborder="0" style="border:0"\n  src="https://www.google.com.sg/maps/@1.3437459,103.8240449,11z?hl=en" allowfullscreen>\n</iframe>',
            items: [
                {
                    xtype: 'form',
                    id: 'kerberosHomePanel',
                    itemId: 'kerberosHomePanel',
                    bodyPadding: 10,
                    title: 'Find Shipment',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    width: 343,
                                    items: [
                                        {
                                        	xtype: 'numberfield',
                                            id: 'viewBkgPanel',
                                            itemId: 'viewBkgPanel',
                                            fieldLabel: 'Booking Number',
                                            name:'bkgNum',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'From City',
                                            name:'fromCity',
                                            store: [
                                                'MNL',
                                                'HKG',
                                                'ZHA',
                                                'USA'
                                            ],
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'From Date',
                                            labelWidth: 120
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Container Number',
                                            name:'cntrNum',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'To City',
                                            name:'toCity',
                                            store: [
                                                'MNL',
                                                'HKG',
                                                'ZHA',
                                                'USA'
                                            ],
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'To Date',
                                            labelWidth: 120
                                        },
                                        {
                                            xtype: 'toolbar',
                                            padding: '',
                                            layout: {
                                                type: 'hbox',
                                                padding: 5
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbfill',
                                                    flex: 1,
                                                    width: 235
                                                },
                                                {
                                                    xtype: 'button',
                                                    dock: 'right',
                                                    style: {
                                                        background: '#FFFFFF'
                                                    },
                                                    scale: 'medium',
                                                    text: 'Search',
                                                    id: 'searchBkgBtn',
                                                    itemId: 'searchBkgBtn'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            flex: 1,
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'bkgGrid',
                    flex: 1,
                    padding: 10,
                    bodyPadding: '',
                    title: '',
                    store: 'AllBookingsStore',
                    autoLoad: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'shipmentNum',
                            text: 'Booking Number'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'fromCity',
                            text: 'From City'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'toCity',
                            text: 'To City'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'fromDate',
                            text: 'From Date'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'toDate',
                            text: 'To Date'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'shipper',
                            text: 'Shipper'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'consignee',
                            text: 'Consignee'
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    style: {
                                        background: '#FFFFFF'
                                    },
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    style: {
                                        background: '#FFFFFF'
                                    },
                                    text: 'MyButton'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1
        }
    ]

});